kiwi-postgis: AsSVG Class Reference
AsSVG Class Reference
Public Member Functions
String getURI ()
boolean isSupported (KiWiDialect dialect)
Return true if this function has available native support for the given dialect.
String getNative (KiWiDialect dialect, String... args)
Return a string representing how this GeoSPARQL function is translated into SQL (Postgis Function) in the given dialect.
ValueType getReturnType ()
Get the return type of the function.
ValueType getArgumentType (int arg)
Get the argument type of the function for the arg'th argument (starting to count at 0).
int getMinArgs ()
Return the minimum number of arguments this function requires.
int getMaxArgs ()
Return the maximum number of arguments this function can take.
String operation (Geometry geom)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Static Package Functions
[static initializer]
Member Function Documentation
[static initializer]()
[static initializer] () static package
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References LiteralRegistry.getLiteral(), and GeometricStringExportFunction.operation().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         String result = operation(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }
getArgumentType()
ValueType getArgumentType (int arg)
Get the argument type of the function for the arg'th argument (starting to count at 0).
This is needed for SQL type casting inside KiWi.
Parameters
arg
Returns
References ValueType.GEOMETRY.
       {
         return ValueType.GEOMETRY;
     }
getMaxArgs()
int getMaxArgs ()
Return the maximum number of arguments this function can take.
Returns
{
         return 1;
     }
getMinArgs()
int getMinArgs ()
Return the minimum number of arguments this function requires.
Returns
{
         return 1;
     }
getNative()
String getNative (KiWiDialect dialect, String... args)
Return a string representing how this GeoSPARQL function is translated into SQL (Postgis Function) in the given dialect.
Parameters
dialect
args
Returns
References FN_POSTGIS.ST_ASSVG.
{
         if (dialect instanceof PostgreSQLDialect) {
             if (args.length == 1) {
                 String geom1 = args[0];
                 String SRID_default = "4326";
                 /*
                  * The following condition is required to read WKT  inserted directly into args[0] and create a geometries with SRID
                  * POINT, MULTIPOINT, LINESTRING ... and MULTIPOLYGON conditions:
                  *   example: geof:convexHull("POLYGON(( -7 43, -2 43, -2 38, -7 38, -7 43))"^^geo:wktLiteral)
                  * st_AsText condition: It is to use the geometry that is the result of another function geosparql.
                  *   example: geof:convexHull(geof:buffer(?geom, 50, units:meter))
                  */
                 if (args[0].contains("POINT") || args[0].contains("MULTIPOINT") || args[0].contains("LINESTRING") || args[0].contains("MULTILINESTRING") || args[0].contains("POLYGON") || args[0].contains("MULTIPOLYGON") || args[0].contains("ST_AsText")) {
                     geom1 = String.format("ST_GeomFromText(%s,%s)", args[0], SRID_default);
                 }
                 return String.format("ST_AsSVG(%s)", geom1);
             }
         }
         throw new UnsupportedOperationException(FN_POSTGIS.ST_ASSVG.toString()+" function not supported by dialect " + dialect);
     }
getReturnType()
ValueType getReturnType ()
Get the return type of the function.
This is needed for SQL type casting inside KiWi.
Returns
References ValueType.STRING.
{
         return ValueType.STRING;
     }
getURI()
String getURI ()
References FN_POSTGIS.ST_ASSVG.
{
         return FN_POSTGIS.ST_ASSVG.stringValue();
     }
isSupported()
boolean isSupported (KiWiDialect dialect)
Return true if this function has available native support for the given dialect.
Parameters
dialect
Returns
{
         return dialect instanceof PostgreSQLDialect;
     }
operation()
String operation (Geometry geom) inherited
References SVGWriter.write().
{
         SVGWriter writer=new SVGWriter();
         String result=writer.write(geom);
         return result.toString();
         }