kiwi-postgis: Touches Class Reference
Touches Class Reference
Public Member Functions
String getURI ()
boolean isSupported (KiWiDialect dialect)
Return true if this function has available native support for the given dialect.
String getNative (KiWiDialect dialect, String... args)
Return a string representing how this GeoSPARQL function is translated into SQL (Postgis Function) in the given dialect.
ValueType getReturnType ()
Get the return type of the function.
ValueType getArgumentType (int arg)
Get the argument type of the function for the arg'th argument (starting to count at 0).
int getMinArgs ()
Return the minimum number of arguments this function requires.
int getMaxArgs ()
Return the maximum number of arguments this function can take.
Boolean relation (Value v1, Value v2)
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Static Public Member Functions
static Boolean vectorOrRaster (Literal lit)
static Literal getLiteral (Function func, Value v) throws ValueExprEvaluationException
Static Public Attributes
static Set< String > rasterLiteralURIs =new TreeSet<String>()
static Set< String > vectorLiteralURIs =new TreeSet<String>()
Static Package Functions
[static initializer]
Member Function Documentation
[static initializer]()
[static initializer] () static package
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException inherited
References RasterVectorRelationBinaryFunction.relation().
{
                 // TODO Auto-generated method stub
                 return null;
         }
getArgumentType()
ValueType getArgumentType (int arg)
Get the argument type of the function for the arg'th argument (starting to count at 0).
This is needed for SQL type casting inside KiWi.
Parameters
arg
Returns
References ValueType.GEOMETRY.
       {
         return ValueType.GEOMETRY;
     }
getLiteral()
static Literal getLiteral (Function func, Value v) throws ValueExprEvaluationException static inherited
Referenced by Contains.relation(), Within.relation(), CoveredBy.relation(), Crosses.relation(), Disjoint.relation(), Equals.relation(), Intersects.relation(), Overlaps.relation(), Touches.relation(), and ContainsProperly.relation().
{
                 if (!(v instanceof Literal)) {
                         throw new ValueExprEvaluationException("Invalid argument for " + func.getURI() + ": " + v);
                 }
                 Literal lit = (Literal) v;
                 return lit;
         }
getMaxArgs()
int getMaxArgs ()
Return the maximum number of arguments this function can take.
Returns
{
         return 2;
     }
getMinArgs()
int getMinArgs ()
Return the minimum number of arguments this function requires.
Returns
{
         return 2;
     }
getNative()
String getNative (KiWiDialect dialect, String... args)
Return a string representing how this GeoSPARQL function is translated into SQL (Postgis Function) in the given dialect.
Parameters
dialect
args
Returns
References FN_POSTGIS.st_rast_Touches.
{
         if (dialect instanceof PostgreSQLDialect) {
             if (args.length == 2) {
                 String geom1 = args[0];
                 String geom2 = args[1];
                 String SRID_default = "4326";
                 /*
                  * The following condition is required to read WKT  inserted directly into args[0] and create a geometries with SRID
                  * POINT, MULTIPOINT, LINESTRING ... and MULTIPOLYGON conditions:
                  *   example: geof:convexHull("POLYGON(( -7 43, -2 43, -2 38, -7 38, -7 43))"^^geo:wktLiteral)
                  * st_AsText condition: It is to use the geometry that is the result of another function geosparql.
                  *   example: geof:convexHull(geof:buffer(?geom, 50, units:meter))
                  */
                 if (args[0].contains("POINT") || args[0].contains("MULTIPOINT") || args[0].contains("LINESTRING") || args[0].contains("MULTILINESTRING") || args[0].contains("POLYGON") || args[0].contains("MULTIPOLYGON") || args[0].contains("ST_AsText")) {
                     geom1 = String.format("ST_GeomFromText(%s,%s)", args[0], SRID_default);
                 }
                 if (args[1].contains("POINT") || args[1].contains("MULTIPOINT") || args[1].contains("LINESTRING") || args[1].contains("MULTILINESTRING") || args[1].contains("POLYGON") || args[1].contains("MULTIPOLYGON") || args[1].contains("ST_AsText")) {
                     geom2 = String.format("ST_GeomFromText(%s,%s)", args[1], SRID_default);
                 }
                 return String.format("ST_Touches(%s,%s)", geom1,geom2);
             }
         }
         throw new UnsupportedOperationException(FN_POSTGIS.st_rast_Touches.toString()+" function not supported by dialect " + dialect);
     }
getReturnType()
ValueType getReturnType ()
Get the return type of the function.
This is needed for SQL type casting inside KiWi.
Returns
References ValueType.BOOL.
{
         return ValueType.BOOL;
     }
getURI()
String getURI ()
References FN_POSTGIS.st_rast_Touches.
{
         return FN_POSTGIS.st_rast_Touches.stringValue();
     }
isSupported()
boolean isSupported (KiWiDialect dialect)
Return true if this function has available native support for the given dialect.
Parameters
dialect
Returns
{
         return dialect instanceof PostgreSQLDialect;
     }
relation()
Boolean relation (Value v1, Value v2) inherited
References RasterVectorRelationBinaryFunction.getLiteral(), LiteralRegistry.getLiteral(), VectorLiteral.read(), RasterLiteral.read(), LiteralUtils.toGeometry(), and RasterVectorRelationBinaryFunction.vectorOrRaster().
{
                 Literal lit1=getLiteral(this, v1);
                 Literal lit2=getLiteral(this, v2);
                 Boolean type=vectorOrRaster(getLiteral(this, v1));
                 Boolean type2=vectorOrRaster(getLiteral(this, v2));
                 if(type==null || type2==null) {
                         return null;
                 }else if(type && type2) {
                         VectorLiteral vec1=(VectorLiteral) LiteralRegistry.getLiteral(lit1.getDatatype().toString());
                         VectorLiteral vec2=(VectorLiteral) LiteralRegistry.getLiteral(lit2.getDatatype().toString());
                         return vec1.read(v1.stringValue()).touches(vec2.read(v2.stringValue()));
                 }else if(type && !type2) {
                         VectorLiteral vec1=(VectorLiteral) LiteralRegistry.getLiteral(lit1.getDatatype().toString());
                         RasterLiteral vec2=(RasterLiteral) LiteralRegistry.getLiteral(lit2.getDatatype().toString());
                         return vec1.read(v1.stringValue()).touches(LiteralUtils.toGeometry(vec2.read(v2.stringValue()).getGridGeometry().getEnvelope()));
                 }else if(!type && type2) {
                         RasterLiteral vec1=(RasterLiteral) LiteralRegistry.getLiteral(lit1.getDatatype().toString());
                         VectorLiteral vec2=(VectorLiteral) LiteralRegistry.getLiteral(lit2.getDatatype().toString());
                         return LiteralUtils.toGeometry(((GridCoverage)vec1.read(v1.stringValue())).getGridGeometry().getEnvelope()).touches(vec2.read(v2.stringValue()));
                 }else {
                         RasterLiteral vec1=(RasterLiteral) LiteralRegistry.getLiteral(lit1.getDatatype().toString());
                         RasterLiteral vec2=(RasterLiteral) LiteralRegistry.getLiteral(lit2.getDatatype().toString());
                         return LiteralUtils.toGeometry(((GridCoverage)vec1.read(v1.stringValue())).getGridGeometry().getEnvelope()).touches(LiteralUtils.toGeometry(vec2.read(v2.stringValue()).getGridGeometry().getEnvelope()));
                 }
         }
vectorOrRaster()
static Boolean vectorOrRaster (Literal lit) static inherited
References LiteralRegistry.literals.
Referenced by Contains.relation(), Within.relation(), CoveredBy.relation(), Crosses.relation(), Disjoint.relation(), Equals.relation(), Intersects.relation(), Overlaps.relation(), Touches.relation(), and ContainsProperly.relation().
{
                 if(LiteralRegistry.literals.containsKey(lit.getDatatype().toString())) {
                         LiteralType lite=LiteralRegistry.literals.get(lit.getDatatype().toString());
                         if(lite instanceof VectorLiteral) {
                                 return true;
                         }else if(lite instanceof RasterLiteral) {
                                 return false;
                         }
                 }
                 return null;
         }
Member Data Documentation
rasterLiteralURIs
Set<String> rasterLiteralURIs =new TreeSet<String>() static inherited
vectorLiteralURIs
Set<String> vectorLiteralURIs =new TreeSet<String>() static inherited