kiwi-postgis: POSTGIS Class Reference
POSTGIS Class Reference
Static Public Attributes
static final String NAMESPACE ="http://www.opengis.net/ont/geosparql#"
static final ValueFactory factory = new ValueFactoryImpl()
static final URI ST_DWITHIN3D =factory.createURI(NAMESPACE, "ST_3DDWithin")
static final URI ST_CLOSESTPOINT3D =factory.createURI(NAMESPACE, "ST_ClosestPoint3D")
static final URI ST_LONGESTLINE3D =factory.createURI(NAMESPACE, "ST_LongestLine3D")
static final URI ST_MAXDISTANCE3D =factory.createURI(NAMESPACE, "ST_MaxDistance3D")
static final URI ST_SHORTESTLINE3D =factory.createURI(NAMESPACE, "ST_ShortestLine3D")
static final URI ST_ACCUM =factory.createURI(NAMESPACE, "ST_Accum")
static final URI ST_ADDBAND =factory.createURI(NAMESPACE, "ST_AddBand")
static final URI ST_ADDPOINT =factory.createURI(NAMESPACE, "ST_AddPoint")
static final URI ST_ADDZ =factory.createURI(NAMESPACE, "ST_AddZ")
static final URI ST_ASBINARY =factory.createURI(NAMESPACE, "ST_AsBinary")
static final URI ST_ASENCODEDPOLYLINE =factory.createURI(NAMESPACE, "ST_AsEncodedPolyline")
static final URI ST_ASHEXEWKB =factory.createURI(NAMESPACE, "ST_AsHEXEWKB")
static final URI ST_ASKML =factory.createURI(NAMESPACE, "ST_AsKML")
static final URI ST_ASGML =factory.createURI(NAMESPACE, "ST_AsGML")
static final URI ST_ASGEOHASH =factory.createURI(NAMESPACE, "ST_AsGeoHash")
static final URI ST_ASGEOURI =factory.createURI(NAMESPACE, "ST_AsGeoURI")
static final URI ST_ASGEOBUF =factory.createURI(NAMESPACE, "ST_AsGeoBuf")
static final URI ST_ASGEOJSON =factory.createURI(NAMESPACE, "ST_AsGeoJSON")
static final URI ST_ASGEOJSONLD =factory.createURI(NAMESPACE, "ST_AsGeoJSONLD")
static final URI ST_ASGEORSS =factory.createURI(NAMESPACE, "ST_AsGeoRSS")
static final URI ST_ASGPX =factory.createURI(NAMESPACE, "ST_AsGPX")
static final URI st_aspect =factory.createURI(NAMESPACE, "ST_Aspect")
static final URI ST_ASPOLYSHAPE =factory.createURI(NAMESPACE, "ST_AsPolyshape")
static final URI ST_ASTIFF =factory.createURI(NAMESPACE, "ST_AsTIFF")
static final URI ST_ASTOPOJSON =factory.createURI(NAMESPACE, "ST_AsTopoJSON")
static final URI ST_ASJPG =factory.createURI(NAMESPACE, "ST_AsJPG")
static final URI ST_ASLATLONTEXT =factory.createURI(NAMESPACE, "ST_AsLatLonText")
static final URI ST_ASPNG =factory.createURI(NAMESPACE, "ST_AsPNG")
static final URI ST_ASMVT =factory.createURI(NAMESPACE, "ST_AsMVT")
static final URI ST_ASMVTGEOM =factory.createURI(NAMESPACE, "ST_AsMVTGeom")
static final URI ST_ASSVG =factory.createURI(NAMESPACE, "ST_AsSVG")
static final URI ST_ASTEXT =factory.createURI(NAMESPACE, "ST_AsText")
static final URI ST_ASTEXTRAW =factory.createURI(NAMESPACE, "ST_AsTextRaw")
static final URI ST_ASTEXTROUND =factory.createURI(NAMESPACE, "ST_AsTextRound")
static final URI ST_ASTWKB =factory.createURI(NAMESPACE, "ST_AsTWKB")
static final URI ST_ASWKB =factory.createURI(NAMESPACE, "ST_AsWKB")
static final URI ST_ASWKT =factory.createURI(NAMESPACE, "ST_AsWKT")
static final URI ST_ASX3D =factory.createURI(NAMESPACE, "ST_AsX3D")
static final URI ST_AREA =factory.createURI(NAMESPACE, "ST_Area")
static final URI ST_AREA3D =factory.createURI(NAMESPACE, "ST_Area3D")
static final URI ST_AREASIMILARITY =factory.createURI(NAMESPACE, "ST_AreaSimilarity")
static final URI ST_AZIMUTH =factory.createURI(NAMESPACE, "ST_Azimuth")
static final URI st_bboxabove =factory.createURI(NAMESPACE,"ST_BBOXAbove")
static final URI st_bboxbelow = factory.createURI(NAMESPACE,"ST_BBOXBelow")
static final URI st_bboxcontains = factory.createURI(NAMESPACE,"ST_BBOXContains")
static final URI st_bboxdistance = factory.createURI(NAMESPACE,"ST_BBOXDistance")
static final URI st_bboxequals = factory.createURI(NAMESPACE, "ST_BBOXEquals")
static final URI st_bboxfpintersects = factory.createURI(NAMESPACE, "ST_BBOXFPIntersects")
static final URI st_bboxintersect = factory.createURI(NAMESPACE, "ST_BBOXIntersects")
static final URI st_bboxiscontainedby =factory.createURI(NAMESPACE, "ST_BBOXIsContainedBy")
static final URI st_bboxleftof = factory.createURI(NAMESPACE, "ST_BBOXLeftOf")
static final URI st_bboxoverlapsabove = factory.createURI(NAMESPACE, "ST_BBOXOverlapsAbove")
static final URI st_bboxoverlapsbelow =factory.createURI(NAMESPACE, "ST_BBOXOverlapsBelow")
static final URI st_bboxoverlapsleft = factory.createURI(NAMESPACE ,"ST_BBOXOverlapsLeft")
static final URI st_bboxoverlapsright = factory.createURI(NAMESPACE, "ST_BBOXOverlapsRight")
static final URI st_bboxrightof = factory.createURI(NAMESPACE, "ST_BBOXRightOf")
static final URI ST_BAND =factory.createURI(NAMESPACE, "ST_Band")
static final URI ST_BANDMETADATA =factory.createURI(NAMESPACE, "ST_BandMetaData")
static final URI ST_BANDNODATAVALUE =factory.createURI(NAMESPACE, "ST_BandNoDataValue")
static final URI ST_BANDPIXELTYPE =factory.createURI(NAMESPACE, "ST_BandPixelType")
static final URI ST_BEZIERSMOOTHING =factory.createURI(NAMESPACE, "ST_BezierSmoothing")
static final URI ST_BOUNDARY =factory.createURI(NAMESPACE, "ST_Boundary")
static final URI ST_BOUNDINGDIAGONAL =factory.createURI(NAMESPACE, "ST_BoundingDiagonal")
static final URI ST_CENTROID =factory.createURI(NAMESPACE, "ST_Centroid")
static final URI ST_CENTROIDDISTANCE =factory.createURI(NAMESPACE, "ST_CentroidDistance")
static final URI ST_CHAIKINSMOOTHING =factory.createURI(NAMESPACE, "ST_ChaikinSmoothing")
static final URI ST_CLIP =factory.createURI(NAMESPACE, "ST_Clip")
static final URI ST_CLIPBYBOX2D =factory.createURI(NAMESPACE, "ST_ClipByBox2D")
static final URI ST_CLOSESTPOINT =factory.createURI(NAMESPACE, "ST_ClosestPoint")
static final URI ST_CLOSESTPOINTOFAPPROACH =factory.createURI(NAMESPACE, "ST_ClosestPointOfApproach")
static final URI ST_CLUSTERINTERSECTING =factory.createURI(NAMESPACE, "ST_ClusterIntersecting")
static final URI ST_CLUSTERKMEANS =factory.createURI(NAMESPACE, "ST_ClusterKMeans")
static final URI ST_CLUSTERWITHIN =factory.createURI(NAMESPACE, "ST_ClusterWithin")
static final URI ST_COLLECTIONHOMOGENIZE =factory.createURI(NAMESPACE, "ST_CollectionHomogenize")
static final URI ST_COMPACTNESSRATIO =factory.createURI(NAMESPACE, "ST_CompactnessRatio")
static final URI ST_CONCAVEHULL =factory.createURI(NAMESPACE, "ST_ConcaveHull")
static final URI ST_CONTAINS =factory.createURI(NAMESPACE, "ST_Contains")
static final URI ST_CONTAINSPROPERLY =factory.createURI(NAMESPACE, "ST_ContainsProperly")
static final URI ST_CONVEXHULL =factory.createURI(NAMESPACE, "ST_ConvexHull")
static final URI ST_COUNT =factory.createURI(NAMESPACE, "ST_Count")
static final URI ST_CURVETOLINE =factory.createURI(NAMESPACE, "ST_CurveToLine")
static final URI st_curvature =factory.createURI(NAMESPACE, "ST_Curvature")
static final URI st_crop =factory.createURI(NAMESPACE, "ST_Crop")
static final URI ST_DENSIFY =factory.createURI(NAMESPACE, "ST_Densify")
static final URI ST_DELAUNAYTRIANGLES =factory.createURI(NAMESPACE, "ST_DelaunayTriangles")
static final URI ST_DIMENSION =factory.createURI(NAMESPACE, "ST_Dimension")
static final URI ST_DISTANCE =factory.createURI(NAMESPACE, "ST_Distance")
static final URI ST_DISTANCE3D =factory.createURI(NAMESPACE, "ST_Distance3D")
static final URI ST_DISTANCESPHERE =factory.createURI(NAMESPACE, "ST_DistanceSphere")
static final URI ST_DWITHIN =factory.createURI(NAMESPACE, "ST_DWithin")
static final URI ST_ENDPOINT =factory.createURI(NAMESPACE, "ST_EndPoint")
static final URI ST_EQUALS =factory.createURI(NAMESPACE, "ST_Equals")
static final URI ST_EQUALSNORM =factory.createURI(NAMESPACE, "ST_EqualsNorm")
static final URI ST_EQUALSTOPO =factory.createURI(NAMESPACE, "ST_EqualsTopo")
static final URI ST_EQUALSRS =factory.createURI(NAMESPACE, "ST_EqualSRS")
static final URI ST_EPSGTOSRID =factory.createURI(NAMESPACE, "ST_EPSGToSRID")
static final URI ST_FILTERBYM =factory.createURI(NAMESPACE, "ST_FilterByM")
static final URI ST_FILTERBYT =factory.createURI(NAMESPACE, "ST_FilterByT")
static final URI st_flip =factory.createURI(NAMESPACE, "ST_Flip")
static final URI ST_FLIPCOORDINATES =factory.createURI(NAMESPACE, "ST_FlipCoordinates")
static final URI ST_flowdirection =factory.createURI(NAMESPACE, "ST_FlowDirection")
static final URI st_equals =factory.createURI(NAMESPACE, "ST_Equals")
static final URI st_equalsNorm =factory.createURI(NAMESPACE, "ST_EqualNorm")
static final URI st_equalsTopo =factory.createURI(NAMESPACE, "ST_EqualTopo")
static final URI st_equalSRS =factory.createURI(NAMESPACE, "ST_EqualSRS")
static final URI st_epsgToSRID =factory.createURI(NAMESPACE, "ST_EPSGToSRID")
static final URI st_exteriorRing =factory.createURI(NAMESPACE, "ST_ExteriorRing")
static final URI st_filterByM =factory.createURI(NAMESPACE, "ST_FilterByM")
static final URI st_filterByT =factory.createURI(NAMESPACE, "ST_FilterByT")
static final URI st_flipCoordinates =factory.createURI(NAMESPACE, "ST_FlipCoordinates")
static final URI st_force2d =factory.createURI(NAMESPACE, "ST_Force2D")
static final URI st_force3d =factory.createURI(NAMESPACE, "ST_Force3D")
static final URI st_force3dm =factory.createURI(NAMESPACE, "ST_Force3DM")
static final URI st_force3dz =factory.createURI(NAMESPACE, "ST_Force3D")
static final URI st_force4d =factory.createURI(NAMESPACE, "ST_Force4D")
static final URI st_forceCollection =factory.createURI(NAMESPACE, "ST_ForceCollection")
static final URI st_forceCurve =factory.createURI(NAMESPACE, "ST_ForceCurve")
static final URI st_forceLHR =factory.createURI(NAMESPACE, "ST_ForceLHR")
static final URI st_forcePolygonCW =factory.createURI(NAMESPACE, "ST_ForcePolygonCW")
static final URI st_forcePolygonCCW =factory.createURI(NAMESPACE, "ST_ForcePolygonCCW")
static final URI st_forceSFS =factory.createURI(NAMESPACE, "ST_ForceSFS")
static final URI st_frechetDistance =factory.createURI(NAMESPACE, "ST_FrechetDistance")
static final URI st_generatePoints =factory.createURI(NAMESPACE, "ST_GeneratePoints")
static final URI st_geohash =factory.createURI(NAMESPACE, "ST_AsGeoHash")
static final URI st_geomFromGeoJSON =factory.createURI(NAMESPACE, "ST_GeomFromGeoJSON")
static final URI st_geomFromGeoHash =factory.createURI(NAMESPACE, "ST_GeomFromGeoHash")
static final URI st_geomFromGML =factory.createURI(NAMESPACE, "ST_GeomFromGML")
static final URI st_geomFromKML =factory.createURI(NAMESPACE, "ST_GeomFromKML")
static final URI st_geomFromWKB =factory.createURI(NAMESPACE, "ST_GeomFromWKB")
static final URI st_geomFromText =factory.createURI(NAMESPACE, "ST_GeomFromText")
static final URI st_geometricMedian =factory.createURI(NAMESPACE, "ST_GeometricMedian")
static final URI st_geometryN =factory.createURI(NAMESPACE, "ST_GeometryN")
static final URI st_geometryType =factory.createURI(NAMESPACE, "ST_GeometryType")
static final URI st_gmlToSQL =factory.createURI(NAMESPACE, "ST_GeomFromGML")
static final URI st_hasNoBand =factory.createURI(NAMESPACE, "ST_HasNoBand")
static final URI ST_hasHorizontalCRS =factory.createURI(NAMESPACE, "ST_HasHorizontalCRS")
static final URI st_hasRepeatedPoints =factory.createURI(NAMESPACE, "ST_HasRepeatedPoints")
static final URI st_hausdorffDistance =factory.createURI(NAMESPACE, "ST_HausdorffDistance")
static final URI st_height =factory.createURI(NAMESPACE, "ST_Height")
static final URI st_hillshade =factory.createURI(NAMESPACE, "ST_Hillshade")
static final URI st_histogram = factory.createURI(NAMESPACE,"ST_Histogram")
static final URI st_interiorRingN =factory.createURI(NAMESPACE, "ST_InteriorRingN")
static final URI st_interpolatePoint =factory.createURI(NAMESPACE, "ST_InterpolatePoint")
static final URI st_intersectionPercentage =factory.createURI(NAMESPACE, "ST_IntersectionPercentage")
static final URI st_is3D =factory.createURI(NAMESPACE, "ST_Is3D")
static final URI st_isCollection =factory.createURI(NAMESPACE, "ST_IsCollection")
static final URI st_isClosed =factory.createURI(NAMESPACE, "ST_IsClosed")
static final URI st_isConvex =factory.createURI(NAMESPACE, "ST_IsConvex")
static final URI st_isEmpty =factory.createURI(NAMESPACE, "ST_IsEmpty")
static final URI st_isGrayscale =factory.createURI(NAMESPACE, "ST_IsGrayscale")
static final URI st_isIndexed =factory.createURI(NAMESPACE, "ST_IsIndexed")
static final URI st_isTiled =factory.createURI(NAMESPACE, "ST_IsTiled")
static final URI st_isTranslucent =factory.createURI(NAMESPACE, "ST_IsTranslucent")
static final URI st_isLocationOnEdge =factory.createURI(NAMESPACE, "ST_IsLocationOnEdge")
static final URI st_isMeasured =factory.createURI(NAMESPACE, "ST_IsMeasured")
static final URI st_isMorePrecise =factory.createURI(NAMESPACE, "ST_IsMorePrecise")
static final URI st_isNodingValid =factory.createURI(NAMESPACE, "ST_IsNodingValid")
static final URI st_isPointOnLine =factory.createURI(NAMESPACE, "ST_IsPointOnLine")
static final URI st_isPointInRing =factory.createURI(NAMESPACE, "ST_IsPointInRing")
static final URI st_isPolygonCW =factory.createURI(NAMESPACE, "ST_IsPolygonCW")
static final URI st_isPolygonCCW =factory.createURI(NAMESPACE, "ST_IsPolygonCCW")
static final URI st_isRectangle =factory.createURI(NAMESPACE, "ST_IsRectangle")
static final URI st_isRing =factory.createURI(NAMESPACE, "ST_IsRing")
static final URI st_isSimple =factory.createURI(NAMESPACE, "ST_IsSimpleFF")
static final URI st_isValid =factory.createURI(NAMESPACE, "ST_IsValidFF")
static final URI st_isValidTrajectory =factory.createURI(NAMESPACE, "ST_IsValidTrajectory")
static final URI st_isValidReason =factory.createURI(NAMESPACE, "ST_IsValidReason")
static final URI st_isValidDetail =factory.createURI(NAMESPACE, "ST_IsValidDetail")
static final URI st_Length =factory.createURI(NAMESPACE, "ST_Length")
static final URI st_Length2D =factory.createURI(NAMESPACE, "ST_Length")
static final URI st_Length3D =factory.createURI(NAMESPACE, "ST_Length3D")
static final URI st_LengthToPoint =factory.createURI(NAMESPACE, "ST_LengthToPoint")
static final URI st_lineCrossingDirection =factory.createURI(NAMESPACE, "ST_LineCrossingDirection")
static final URI st_lineFromEncodedPolyline =factory.createURI(NAMESPACE, "ST_LineFromEncodedPolyline")
static final URI st_lineFromMultiPoint =factory.createURI(NAMESPACE, "ST_LineFromMultiPoint")
static final URI st_lineFromWKB =factory.createURI(NAMESPACE, "ST_LineFromWKB")
static final URI st_lineFromWKT =factory.createURI(NAMESPACE, "ST_LineFromText")
static final URI st_lineFromText =factory.createURI(NAMESPACE, "ST_LineFromText")
static final URI st_lineInterpolatePoint =factory.createURI(NAMESPACE, "ST_LineInterpolatePoint")
static final URI st_lineInterpolatePoints =factory.createURI(NAMESPACE, "ST_LineInterpolatePoints")
static final URI st_lineLocatePoint =factory.createURI(NAMESPACE, "ST_LineLocatePoint")
static final URI st_lineLength3D =factory.createURI(NAMESPACE, "ST_LineLength3D")
static final URI st_lineMerge =factory.createURI(NAMESPACE, "ST_LineMerge")
static final URI st_lineSelfIntersectionPoint =factory.createURI(NAMESPACE, "ST_LineSelfIntersectionPoint")
static final URI st_lineSubstring =factory.createURI(NAMESPACE, "ST_LineSubstring")
static final URI st_lineToCurve =factory.createURI(NAMESPACE, "ST_LineToCurve")
static final URI st_locateAlong =factory.createURI(NAMESPACE, "ST_LocateAlong")
static final URI st_locateBetween =factory.createURI(NAMESPACE, "ST_LocateBetween")
static final URI st_locateBetweenElevations =factory.createURI(NAMESPACE, "ST_LocateBetweenElevations")
static final URI st_longestLine =factory.createURI(NAMESPACE, "ST_LongestLine")
static final URI st_m =factory.createURI(NAMESPACE, "ST_M")
static final URI st_maxDistance =factory.createURI(NAMESPACE, "ST_MaxDistance")
static final URI st_maxDistance3D =factory.createURI(NAMESPACE, "ST_MaxDistance3D")
static final URI st_makeBox2D =factory.createURI(NAMESPACE, "ST_MakeBox2D")
static final URI st_makeBox3D =factory.createURI(NAMESPACE, "ST_MakeBox3D")
static final URI st_makeCircle =factory.createURI(NAMESPACE, "ST_MakeCircle")
static final URI st_makeEllipse =factory.createURI(NAMESPACE, "ST_MakeEllipse")
static final URI st_makeEmptyCoverage =factory.createURI(NAMESPACE, "ST_MakeEmptyCoverage")
static final URI st_makeEmptyRaster =factory.createURI(NAMESPACE, "ST_MakeEmptyRaster")
static final URI st_makeEnvelope =factory.createURI(NAMESPACE, "ST_MakeEnvelope")
static final URI st_makeLine =factory.createURI(NAMESPACE, "ST_MakeLine")
static final URI st_makePoint =factory.createURI(NAMESPACE, "ST_MakePoint")
static final URI st_makePointM =factory.createURI(NAMESPACE, "ST_MakePointM")
static final URI st_makePolygon =factory.createURI(NAMESPACE, "ST_MakePolygon")
static final URI st_makeValid =factory.createURI(NAMESPACE, "ST_MakeValid")
static final URI st_memsize =factory.createURI(NAMESPACE, "ST_MemSize")
static final URI st_minimumBoundingCircle =factory.createURI(NAMESPACE, "ST_MinimumBoundingCircle")
static final URI st_minimumBoundingCircleCenter =factory.createURI(NAMESPACE, "ST_MinimumBoundingCircleCenter")
static final URI st_minimumBoundingRadius =factory.createURI(NAMESPACE, "ST_MinimumBoundingRadius")
static final URI st_minimumClearance =factory.createURI(NAMESPACE, "ST_MinimumClearance")
static final URI st_minimumClearanceLine =factory.createURI(NAMESPACE, "ST_MinimumClearanceLine")
static final URI st_minimumDiameter =factory.createURI(NAMESPACE, "ST_MinimumDiameter")
static final URI st_minimumDiameterLine =factory.createURI(NAMESPACE, "ST_MinimumDiameterLine")
static final URI st_minimumRectangle =factory.createURI(NAMESPACE, "ST_MinimumRectangle")
static final URI st_minConvexHull =factory.createURI(NAMESPACE, "ST_MinConvexHull")
static final URI st_minTileX =factory.createURI(NAMESPACE, "ST_MinTileX")
static final URI st_minTileY =factory.createURI(NAMESPACE, "ST_MinTileY")
static final URI st_mirror =factory.createURI(NAMESPACE, "ST_Mirror")
static final URI st_mLineFromText =factory.createURI(NAMESPACE, "ST_MLineFromText")
static final URI st_mMin =factory.createURI(NAMESPACE, "ST_MMin")
static final URI st_mMax =factory.createURI(NAMESPACE, "ST_MMax")
static final URI st_mPointFromText =factory.createURI(NAMESPACE, "ST_MPointFromText")
static final URI st_mPolyFromText =factory.createURI(NAMESPACE, "ST_MPolyFromText")
static final URI st_multi =factory.createURI(NAMESPACE, "ST_Multi")
static final URI st_multiplyz =factory.createURI(NAMESPACE, "ST_MultiplyZ")
static final URI st_nearestValue =factory.createURI(NAMESPACE, "ST_NearestValue")
static final URI st_numBands =factory.createURI(NAMESPACE, "ST_NumBands")
static final URI st_numGeometries =factory.createURI(NAMESPACE, "ST_NumGeometries")
static final URI st_numInteriorRings =factory.createURI(NAMESPACE, "ST_NumInteriorRings")
static final URI st_numPatches =factory.createURI(NAMESPACE, "ST_NumPatches")
static final URI st_numPoints =factory.createURI(NAMESPACE, "ST_NumPoints")
static final URI st_numXTiles =factory.createURI(NAMESPACE, "ST_NumXTiles")
static final URI st_numYTiles =factory.createURI(NAMESPACE, "ST_NumYTiles")
static final URI st_nDims =factory.createURI(NAMESPACE, "ST_NDims")
static final URI st_nPoints =factory.createURI(NAMESPACE, "ST_NumPoints")
static final URI st_nRings =factory.createURI(NAMESPACE, "ST_NRings")
static final URI st_node =factory.createURI(NAMESPACE, "ST_Node")
static final URI st_normalize =factory.createURI(NAMESPACE, "ST_Normalize")
static final URI st_octogonalEnvelope =factory.createURI(NAMESPACE, "ST_OctogonalEnvelope")
static final URI st_offsetCurve =factory.createURI(NAMESPACE, "ST_OffsetCurve")
static final URI st_orientation =factory.createURI(NAMESPACE, "ST_Orientation")
static final URI st_orderingEquals =factory.createURI(NAMESPACE, "ST_OrderingEquals")
static final URI st_osmlink =factory.createURI(NAMESPACE, "ST_AsOSMLink")
static final URI st_patchN =factory.createURI(NAMESPACE, "ST_PatchN")
static final URI st_partOfGeometryAfter =factory.createURI(NAMESPACE, "ST_PartOfGeometryAfter")
static final URI st_partOfGeometryBefore =factory.createURI(NAMESPACE, "ST_PartOfGeometryBefore")
static final URI st_perimeter =factory.createURI(NAMESPACE, "ST_Perimeter")
static final URI st_perimeter2D =factory.createURI(NAMESPACE, "ST_Perimeter")
static final URI st_perimeter3D =factory.createURI(NAMESPACE, "ST_Perimeter3D")
static final URI st_pixelAsCentroid =factory.createURI(NAMESPACE, "ST_PixelAsCentroid")
static final URI st_pixelAsCentroids =factory.createURI(NAMESPACE, "ST_PixelAsCentroids")
static final URI st_pixelAsPoint =factory.createURI(NAMESPACE, "ST_PixelAsPoint")
static final URI st_pixelAsPoints =factory.createURI(NAMESPACE, "ST_PixelAsPoints")
static final URI st_pixelAsPolygon =factory.createURI(NAMESPACE, "ST_PixelAsPolygon")
static final URI st_pixelAsPolygons =factory.createURI(NAMESPACE, "ST_PixelAsPolygons")
static final URI st_pixelHeight =factory.createURI(NAMESPACE, "ST_PixelHeight")
static final URI st_pixelOfValue =factory.createURI(NAMESPACE, "ST_PixelOfValue")
static final URI st_pixelWidth =factory.createURI(NAMESPACE, "ST_PixelWidth")
static final URI st_points =factory.createURI(NAMESPACE, "ST_Points")
static final URI st_pointN =factory.createURI(NAMESPACE, "ST_PointN")
static final URI st_pointFromGeoHash =factory.createURI(NAMESPACE, "ST_PointFromGeoHash")
static final URI st_pointFromWKB =factory.createURI(NAMESPACE, "ST_PointFromWKB")
static final URI st_pointFromText =factory.createURI(NAMESPACE, "ST_PointFromText")
static final URI st_pointInsideCircle =factory.createURI(NAMESPACE, "ST_PointInsideCircle")
static final URI st_pointOnSurface =factory.createURI(NAMESPACE, "ST_PointOnSurface")
static final URI st_polygon =factory.createURI(NAMESPACE, "ST_Polygon")
static final URI st_polygonize =factory.createURI(NAMESPACE, "ST_Polygonize")
static final URI st_polygonFromText =factory.createURI(NAMESPACE, "ST_PolygonFromText")
static final URI st_polygonFromWKB =factory.createURI(NAMESPACE, "ST_PolygonFromWKB")
static final URI st_precisionReducer =factory.createURI(NAMESPACE, "ST_PrecisionReducer")
static final URI st_rastFromWKB =factory.createURI(NAMESPACE, "ST_RastFromWKB")
static final URI st_rastFromHexWKB =factory.createURI(NAMESPACE, "ST_RastFromHexWKB")
static final URI st_rast_isEmpty =factory.createURI(NAMESPACE, "ST_IsEmpty")
static final URI st_rast_Contains =factory.createURI(NAMESPACE, "ST_Contains")
static final URI st_rast_Covers =factory.createURI(NAMESPACE, "ST_Covers")
static final URI st_rast_CoveredBy =factory.createURI(NAMESPACE, "ST_CoveredBy")
static final URI st_rast_Crosses =factory.createURI(NAMESPACE, "ST_Crosses")
static final URI st_rast_Disjoint =factory.createURI(NAMESPACE, "ST_Disjoint")
static final URI st_rast_Intersects =factory.createURI(NAMESPACE, "ST_Intersects")
static final URI st_rast_Intersection =factory.createURI(NAMESPACE, "ST_Intersection")
static final URI st_rast_Overlaps =factory.createURI(NAMESPACE, "ST_Overlaps")
static final URI st_rast_srid =factory.createURI(NAMESPACE, "ST_SRID")
static final URI st_rast_Touches =factory.createURI(NAMESPACE, "ST_Touches")
static final URI st_rast_Within =factory.createURI(NAMESPACE, "ST_Within")
static final URI st_rasterToWorldCoord =factory.createURI(NAMESPACE, "ST_RasterToWorldCoord")
static final URI st_rasterToWorldCoordX =factory.createURI(NAMESPACE, "ST_RasterToWorldCoordX")
static final URI st_rasterToWorldCoordY =factory.createURI(NAMESPACE, "ST_RasterToWorldCoordY")
static final URI st_reflect =factory.createURI(NAMESPACE, "ST_Reflect")
static final URI st_relate =factory.createURI(NAMESPACE, "ST_Relate")
static final URI st_relateMatch =factory.createURI(NAMESPACE, "ST_RelateMatch")
static final URI st_removePoint =factory.createURI(NAMESPACE, "ST_RemovePoint")
static final URI st_removePoints =factory.createURI(NAMESPACE, "ST_RemovePoints")
static final URI st_removeRepeatedPoints =factory.createURI(NAMESPACE, "ST_RemoveRepeatedPoints")
static final URI st_reskew =factory.createURI(NAMESPACE, "ST_Reskew")
static final URI st_resample =factory.createURI(NAMESPACE, "ST_Resample")
static final URI st_rescale =factory.createURI(NAMESPACE, "ST_Rescale")
static final URI st_resize =factory.createURI(NAMESPACE, "ST_Resize")
static final URI st_retile =factory.createURI(NAMESPACE, "ST_Retile")
static final URI st_reverse =factory.createURI(NAMESPACE, "ST_Reverse")
static final URI st_rotate =factory.createURI(NAMESPACE, "ST_Rotate")
static final URI st_rotateX =factory.createURI(NAMESPACE, "ST_RotateX")
static final URI st_rotateY =factory.createURI(NAMESPACE, "ST_RotateY")
static final URI st_rotateZ =factory.createURI(NAMESPACE, "ST_RotateZ")
static final URI st_rotation =factory.createURI(NAMESPACE, "ST_Rotation")
static final URI st_roughness =factory.createURI(NAMESPACE, "ST_Roughness")
static final URI st_scale =factory.createURI(NAMESPACE, "ST_Scale")
static final URI st_scaleX =factory.createURI(NAMESPACE, "ST_ScaleX")
static final URI st_scaleY =factory.createURI(NAMESPACE, "ST_ScaleY")
static final URI st_shearTransformation =factory.createURI(NAMESPACE, "ST_ShearTransformation")
static final URI st_segmentize =factory.createURI(NAMESPACE, "ST_Segmentize")
static final URI st_setScale =factory.createURI(NAMESPACE, "ST_SetScale")
static final URI st_setSkew =factory.createURI(NAMESPACE, "ST_SetSkew")
static final URI st_setRotation =factory.createURI(NAMESPACE, "ST_SetRotation")
static final URI st_setGeoReference =factory.createURI(NAMESPACE, "ST_SetGeoReference")
static final URI st_setUpperLeft =factory.createURI(NAMESPACE, "ST_SetUpperLeft")
static final URI st_setPoint =factory.createURI(NAMESPACE, "ST_SetPoint")
static final URI st_setSRID =factory.createURI(NAMESPACE, "ST_SetSRID")
static final URI st_shift =factory.createURI(NAMESPACE, "ST_Shift")
static final URI st_simplify =factory.createURI(NAMESPACE, "ST_Simplify")
static final URI st_simplifyPreserveTopology =factory.createURI(NAMESPACE, "ST_SimplifyPreserveTopology")
static final URI st_simplifyVW =factory.createURI(NAMESPACE, "ST_SimplifyVW")
static final URI st_sharedPaths =factory.createURI(NAMESPACE, "ST_SharedPaths")
static final URI st_shiftLongitude =factory.createURI(NAMESPACE, "ST_ShiftLongitude")
static final URI st_shortestLine =factory.createURI(NAMESPACE, "ST_ShortestLine")
static final URI st_shortestLine3D =factory.createURI(NAMESPACE, "ST_ShortestLine3D")
static final URI st_slope =factory.createURI(NAMESPACE, "ST_Slope")
static final URI st_skewX =factory.createURI(NAMESPACE, "ST_SkewX")
static final URI st_skewY =factory.createURI(NAMESPACE, "ST_SkewY")
static final URI st_snap =factory.createURI(NAMESPACE, "ST_Snap")
static final URI st_split =factory.createURI(NAMESPACE, "ST_Split")
static final URI st_srid =factory.createURI(NAMESPACE, "ST_GetSRIDFF")
static final URI st_sridToEPSG =factory.createURI(NAMESPACE, "ST_SRIDToEPSG")
static final URI st_startPoint =factory.createURI(NAMESPACE, "ST_StartPoint")
static final URI st_straightSkeleton =factory.createURI(NAMESPACE, "ST_StraightSkeleton")
static final URI st_summary =factory.createURI(NAMESPACE, "ST_Summary")
static final URI st_swapOrdinates =factory.createURI(NAMESPACE, "ST_SwapOrdinates")
static final URI st_symDifference =factory.createURI(NAMESPACE, "ST_SymDifference")
static final URI st_tesselate =factory.createURI(NAMESPACE, "ST_Tesselate")
static final URI st_t =factory.createURI(NAMESPACE, "ST_T")
static final URI st_tileGridXOffset = factory.createURI(NAMESPACE, "ST_TileGridXOffset")
static final URI st_tileGridYOffset = factory.createURI(NAMESPACE, "ST_TileGridYOffset")
static final URI st_tileHeight = factory.createURI(NAMESPACE, "ST_TileHeight")
static final URI st_tileWidth = factory.createURI(NAMESPACE, "ST_TileWidth")
static final URI st_tMin =factory.createURI(NAMESPACE, "ST_TMin")
static final URI st_tMax =factory.createURI(NAMESPACE, "ST_TMax")
static final URI st_tpi =factory.createURI(NAMESPACE, "ST_TPI")
static final URI st_tri =factory.createURI(NAMESPACE, "ST_TRI")
static final URI st_transscale =factory.createURI(NAMESPACE, "ST_TransScale")
static final URI st_translate =factory.createURI(NAMESPACE, "ST_Translate")
static final URI st_transform =factory.createURI(NAMESPACE, "ST_Transform")
static final URI st_union =factory.createURI(NAMESPACE, "ST_Union")
static final URI st_unaryUnion =factory.createURI(NAMESPACE, "ST_UnaryUnion")
static final URI st_upperLeftX =factory.createURI(NAMESPACE, "ST_UpperLeftX")
static final URI st_upperLeftY =factory.createURI(NAMESPACE, "ST_UpperLeftY")
static final URI st_vectorize =factory.createURI(NAMESPACE, "ST_Vectorize")
static final URI st_voronoiLines =factory.createURI(NAMESPACE, "ST_VoronoiLines")
static final URI st_voronoiPolygons =factory.createURI(NAMESPACE, "ST_VoronoiPolygons")
static final URI st_width =factory.createURI(NAMESPACE, "ST_Width")
static final URI st_wkbToSQL =factory.createURI(NAMESPACE, "ST_GeomFromWKB")
static final URI st_wktToSQL =factory.createURI(NAMESPACE, "ST_GeomFromText")
static final URI st_worldToRasterCoord =factory.createURI(NAMESPACE, "ST_WorldToRasterCoord")
static final URI st_worldToRasterCoordX =factory.createURI(NAMESPACE, "ST_WorldToRasterCoordX")
static final URI st_worldToRasterCoordY =factory.createURI(NAMESPACE, "ST_WorldToRasterCoordY")
static final URI st_x =factory.createURI(NAMESPACE, "ST_X")
static final URI st_xMin =factory.createURI(NAMESPACE, "ST_XMin")
static final URI st_xMax =factory.createURI(NAMESPACE, "ST_XMax")
static final URI st_y =factory.createURI(NAMESPACE, "ST_Y")
static final URI st_yMin =factory.createURI(NAMESPACE, "ST_YMin")
static final URI st_yMax =factory.createURI(NAMESPACE, "ST_YMax")
static final URI st_z =factory.createURI(NAMESPACE, "ST_Z")
static final URI st_zMin =factory.createURI(NAMESPACE, "ST_ZMin")
static final URI st_zMax =factory.createURI(NAMESPACE, "ST_ZMax")
static final URI st_zmFlag =factory.createURI(NAMESPACE, "ST_Zmflag")
static final String WKB = "WKB"
static final String GeoJSON = "GeoJSON"
static final String GeoJSONLD = "GeoJSONLD"
static final String GeoHash = "GeoHash"
static final String GeoBuf = "GeoBuf"
static final String GeoURI ="GeoURI"
static final String GeoRSS ="GeoRSS"
static final String GMLCOV ="GMLCOV"
static final String KML = "KML"
static final String WKBRaster = "WKBRaster"
static final String GEOTIFF = "GeoTIFF"
static final String EncodedPolyline = "EncodedPolyline"
static final String Polyshape = "Polyshape"
static final String TWKB = "TWKB"
static final String HEXWKB = "HEXWKB"
static final String DXF ="DXF"
static final String MVT = "MVT"
static final String X3D = "X3D"
static final String OSM = "OSM"
static final String HexWKBRaster = "HexWKBRaster"
static final String TopoJSON = "TopoJSON"
static final String TemporalRange ="TemporalRange"
static final String CoverageJSON = "CoverageJSON"
static final String SVG ="SVG"
static final String NETCDF ="NetCDF"
static final String GML ="GML"
static final String WKT ="WKT"
Member Data Documentation
CoverageJSON
final String CoverageJSON = "CoverageJSON" static
DXF
final String DXF ="DXF" static
EncodedPolyline
final String EncodedPolyline = "EncodedPolyline" static
factory
final ValueFactory factory = new ValueFactoryImpl() static
GeoBuf
final String GeoBuf = "GeoBuf" static
GeoHash
final String GeoHash = "GeoHash" static
GeoJSON
final String GeoJSON = "GeoJSON" static
GeoJSONLD
final String GeoJSONLD = "GeoJSONLD" static
GeoRSS
final String GeoRSS ="GeoRSS" static
GEOTIFF
final String GEOTIFF = "GeoTIFF" static
GeoURI
final String GeoURI ="GeoURI" static
GML
final String GML ="GML" static
GMLCOV
final String GMLCOV ="GMLCOV" static
HEXWKB
final String HEXWKB = "HEXWKB" static
HexWKBRaster
final String HexWKBRaster = "HexWKBRaster" static
KML
final String KML = "KML" static
MVT
final String MVT = "MVT" static
NAMESPACE
final String NAMESPACE ="http://www.opengis.net/ont/geosparql#" static
NETCDF
final String NETCDF ="NetCDF" static
OSM
final String OSM = "OSM" static
Polyshape
final String Polyshape = "Polyshape" static
ST_ACCUM
final URI ST_ACCUM =factory.createURI(NAMESPACE, "ST_Accum") static
ST_ADDBAND
final URI ST_ADDBAND =factory.createURI(NAMESPACE, "ST_AddBand") static
Referenced by AddBand.getURI().
ST_ADDPOINT
final URI ST_ADDPOINT =factory.createURI(NAMESPACE, "ST_AddPoint") static
Referenced by AddPoint.getURI().
ST_ADDZ
final URI ST_ADDZ =factory.createURI(NAMESPACE, "ST_AddZ") static
Referenced by AddZ.getURI().
ST_AREA
final URI ST_AREA =factory.createURI(NAMESPACE, "ST_Area") static
Referenced by Area.getURI().
ST_AREA3D
final URI ST_AREA3D =factory.createURI(NAMESPACE, "ST_Area3D") static
Referenced by Area3D.getURI().
ST_AREASIMILARITY
final URI ST_AREASIMILARITY =factory.createURI(NAMESPACE, "ST_AreaSimilarity") static
ST_ASBINARY
final URI ST_ASBINARY =factory.createURI(NAMESPACE, "ST_AsBinary") static
Referenced by AsBinary.getURI().
ST_ASENCODEDPOLYLINE
final URI ST_ASENCODEDPOLYLINE =factory.createURI(NAMESPACE, "ST_AsEncodedPolyline") static
Referenced by AsEncodedPolyline.getURI().
ST_ASGEOBUF
final URI ST_ASGEOBUF =factory.createURI(NAMESPACE, "ST_AsGeoBuf") static
Referenced by AsGeobuf.getURI().
ST_ASGEOHASH
final URI ST_ASGEOHASH =factory.createURI(NAMESPACE, "ST_AsGeoHash") static
Referenced by AsGeoHash.getURI().
ST_ASGEOJSON
final URI ST_ASGEOJSON =factory.createURI(NAMESPACE, "ST_AsGeoJSON") static
Referenced by AsGeoJSON.getURI().
ST_ASGEOJSONLD
final URI ST_ASGEOJSONLD =factory.createURI(NAMESPACE, "ST_AsGeoJSONLD") static
ST_ASGEORSS
final URI ST_ASGEORSS =factory.createURI(NAMESPACE, "ST_AsGeoRSS") static
Referenced by AsGeoRSS.getURI().
ST_ASGEOURI
final URI ST_ASGEOURI =factory.createURI(NAMESPACE, "ST_AsGeoURI") static
Referenced by AsGeoURI.getURI().
ST_ASGML
final URI ST_ASGML =factory.createURI(NAMESPACE, "ST_AsGML") static
Referenced by AsGML.getURI().
ST_ASGPX
final URI ST_ASGPX =factory.createURI(NAMESPACE, "ST_AsGPX") static
Referenced by AsGPX.getURI().
ST_ASHEXEWKB
final URI ST_ASHEXEWKB =factory.createURI(NAMESPACE, "ST_AsHEXEWKB") static
ST_ASJPG
final URI ST_ASJPG =factory.createURI(NAMESPACE, "ST_AsJPG") static
ST_ASKML
final URI ST_ASKML =factory.createURI(NAMESPACE, "ST_AsKML") static
Referenced by AsKML.getURI().
ST_ASLATLONTEXT
final URI ST_ASLATLONTEXT =factory.createURI(NAMESPACE, "ST_AsLatLonText") static
Referenced by AsLatLonText.getURI().
ST_ASMVT
final URI ST_ASMVT =factory.createURI(NAMESPACE, "ST_AsMVT") static
ST_ASMVTGEOM
final URI ST_ASMVTGEOM =factory.createURI(NAMESPACE, "ST_AsMVTGeom") static
st_aspect
final URI st_aspect =factory.createURI(NAMESPACE, "ST_Aspect") static
ST_ASPNG
final URI ST_ASPNG =factory.createURI(NAMESPACE, "ST_AsPNG") static
ST_ASPOLYSHAPE
final URI ST_ASPOLYSHAPE =factory.createURI(NAMESPACE, "ST_AsPolyshape") static
Referenced by AsPolyshape.getURI().
ST_ASSVG
final URI ST_ASSVG =factory.createURI(NAMESPACE, "ST_AsSVG") static
Referenced by AsSVG.getURI().
ST_ASTEXT
final URI ST_ASTEXT =factory.createURI(NAMESPACE, "ST_AsText") static
Referenced by AsText.getURI().
ST_ASTEXTRAW
final URI ST_ASTEXTRAW =factory.createURI(NAMESPACE, "ST_AsTextRaw") static
ST_ASTEXTROUND
final URI ST_ASTEXTROUND =factory.createURI(NAMESPACE, "ST_AsTextRound") static
Referenced by AsTextRound.getURI().
ST_ASTIFF
final URI ST_ASTIFF =factory.createURI(NAMESPACE, "ST_AsTIFF") static
ST_ASTOPOJSON
final URI ST_ASTOPOJSON =factory.createURI(NAMESPACE, "ST_AsTopoJSON") static
ST_ASTWKB
final URI ST_ASTWKB =factory.createURI(NAMESPACE, "ST_AsTWKB") static
ST_ASWKB
final URI ST_ASWKB =factory.createURI(NAMESPACE, "ST_AsWKB") static
ST_ASWKT
final URI ST_ASWKT =factory.createURI(NAMESPACE, "ST_AsWKT") static
ST_ASX3D
final URI ST_ASX3D =factory.createURI(NAMESPACE, "ST_AsX3D") static
Referenced by AsX3D.getURI().
ST_AZIMUTH
final URI ST_AZIMUTH =factory.createURI(NAMESPACE, "ST_Azimuth") static
ST_BAND
final URI ST_BAND =factory.createURI(NAMESPACE, "ST_Band") static
Referenced by Band.getURI().
ST_BANDMETADATA
final URI ST_BANDMETADATA =factory.createURI(NAMESPACE, "ST_BandMetaData") static
Referenced by BandMetadata.getURI().
ST_BANDNODATAVALUE
final URI ST_BANDNODATAVALUE =factory.createURI(NAMESPACE, "ST_BandNoDataValue") static
Referenced by BandNoDataValue.getURI().
ST_BANDPIXELTYPE
final URI ST_BANDPIXELTYPE =factory.createURI(NAMESPACE, "ST_BandPixelType") static
st_bboxabove
final URI st_bboxabove =factory.createURI(NAMESPACE,"ST_BBOXAbove") static
Referenced by BBOXAbove.getURI().
st_bboxbelow
final URI st_bboxbelow = factory.createURI(NAMESPACE,"ST_BBOXBelow") static
Referenced by BBOXBelow.getURI().
st_bboxcontains
final URI st_bboxcontains = factory.createURI(NAMESPACE,"ST_BBOXContains") static
Referenced by BBOXContains.getURI().
st_bboxdistance
final URI st_bboxdistance = factory.createURI(NAMESPACE,"ST_BBOXDistance") static
Referenced by BBOXDistance.getURI().
st_bboxequals
final URI st_bboxequals = factory.createURI(NAMESPACE, "ST_BBOXEquals") static
Referenced by BBOXEquals.getURI().
st_bboxfpintersects
final URI st_bboxfpintersects = factory.createURI(NAMESPACE, "ST_BBOXFPIntersects") static
Referenced by BBOXFPIntersects.getURI().
st_bboxintersect
final URI st_bboxintersect = factory.createURI(NAMESPACE, "ST_BBOXIntersects") static
Referenced by BBOXIntersects.getURI().
st_bboxiscontainedby
final URI st_bboxiscontainedby =factory.createURI(NAMESPACE, "ST_BBOXIsContainedBy") static
Referenced by BBOXIsContainedBy.getURI().
st_bboxleftof
final URI st_bboxleftof = factory.createURI(NAMESPACE, "ST_BBOXLeftOf") static
Referenced by BBOXLeftOf.getURI().
st_bboxoverlapsabove
final URI st_bboxoverlapsabove = factory.createURI(NAMESPACE, "ST_BBOXOverlapsAbove") static
Referenced by BBOXOverlapsAbove.getURI().
st_bboxoverlapsbelow
final URI st_bboxoverlapsbelow =factory.createURI(NAMESPACE, "ST_BBOXOverlapsBelow") static
Referenced by BBOXOverlapsBelow.getURI().
st_bboxoverlapsleft
final URI st_bboxoverlapsleft = factory.createURI(NAMESPACE ,"ST_BBOXOverlapsLeft") static
Referenced by BBOXOverlapsLeft.getURI().
st_bboxoverlapsright
final URI st_bboxoverlapsright = factory.createURI(NAMESPACE, "ST_BBOXOverlapsRight") static
Referenced by BBOXOverlapsRight.getURI().
st_bboxrightof
final URI st_bboxrightof = factory.createURI(NAMESPACE, "ST_BBOXRightOf") static
Referenced by BBOXRightOf.getURI().
ST_BEZIERSMOOTHING
final URI ST_BEZIERSMOOTHING =factory.createURI(NAMESPACE, "ST_BezierSmoothing") static
ST_BOUNDARY
final URI ST_BOUNDARY =factory.createURI(NAMESPACE, "ST_Boundary") static
Referenced by Boundary.getURI().
ST_BOUNDINGDIAGONAL
final URI ST_BOUNDINGDIAGONAL =factory.createURI(NAMESPACE, "ST_BoundingDiagonal") static
Referenced by BoundingDiagonal.getURI().
ST_CENTROID
final URI ST_CENTROID =factory.createURI(NAMESPACE, "ST_Centroid") static
Referenced by Centroid.getURI().
ST_CENTROIDDISTANCE
final URI ST_CENTROIDDISTANCE =factory.createURI(NAMESPACE, "ST_CentroidDistance") static
Referenced by CentroidDistance.getURI().
ST_CHAIKINSMOOTHING
final URI ST_CHAIKINSMOOTHING =factory.createURI(NAMESPACE, "ST_ChaikinSmoothing") static
ST_CLIP
final URI ST_CLIP =factory.createURI(NAMESPACE, "ST_Clip") static
ST_CLIPBYBOX2D
final URI ST_CLIPBYBOX2D =factory.createURI(NAMESPACE, "ST_ClipByBox2D") static
ST_CLOSESTPOINT
final URI ST_CLOSESTPOINT =factory.createURI(NAMESPACE, "ST_ClosestPoint") static
ST_CLOSESTPOINT3D
final URI ST_CLOSESTPOINT3D =factory.createURI(NAMESPACE, "ST_ClosestPoint3D") static
ST_CLOSESTPOINTOFAPPROACH
final URI ST_CLOSESTPOINTOFAPPROACH =factory.createURI(NAMESPACE, "ST_ClosestPointOfApproach") static
ST_CLUSTERINTERSECTING
final URI ST_CLUSTERINTERSECTING =factory.createURI(NAMESPACE, "ST_ClusterIntersecting") static
ST_CLUSTERKMEANS
final URI ST_CLUSTERKMEANS =factory.createURI(NAMESPACE, "ST_ClusterKMeans") static
ST_CLUSTERWITHIN
final URI ST_CLUSTERWITHIN =factory.createURI(NAMESPACE, "ST_ClusterWithin") static
ST_COLLECTIONHOMOGENIZE
final URI ST_COLLECTIONHOMOGENIZE =factory.createURI(NAMESPACE, "ST_CollectionHomogenize") static
ST_COMPACTNESSRATIO
final URI ST_COMPACTNESSRATIO =factory.createURI(NAMESPACE, "ST_CompactnessRatio") static
Referenced by CompactnessRatio.getURI().
ST_CONCAVEHULL
final URI ST_CONCAVEHULL =factory.createURI(NAMESPACE, "ST_ConcaveHull") static
Referenced by ConcaveHull.getURI().
ST_CONTAINS
final URI ST_CONTAINS =factory.createURI(NAMESPACE, "ST_Contains") static
Referenced by Contains.getURI().
ST_CONTAINSPROPERLY
final URI ST_CONTAINSPROPERLY =factory.createURI(NAMESPACE, "ST_ContainsProperly") static
Referenced by ContainsProperly.getURI().
ST_CONVEXHULL
final URI ST_CONVEXHULL =factory.createURI(NAMESPACE, "ST_ConvexHull") static
Referenced by ConvexHull.getURI().
ST_COUNT
final URI ST_COUNT =factory.createURI(NAMESPACE, "ST_Count") static
st_crop
final URI st_crop =factory.createURI(NAMESPACE, "ST_Crop") static
st_curvature
final URI st_curvature =factory.createURI(NAMESPACE, "ST_Curvature") static
ST_CURVETOLINE
final URI ST_CURVETOLINE =factory.createURI(NAMESPACE, "ST_CurveToLine") static
ST_DELAUNAYTRIANGLES
final URI ST_DELAUNAYTRIANGLES =factory.createURI(NAMESPACE, "ST_DelaunayTriangles") static
Referenced by DelaunayTriangles.getURI().
ST_DENSIFY
final URI ST_DENSIFY =factory.createURI(NAMESPACE, "ST_Densify") static
ST_DIMENSION
final URI ST_DIMENSION =factory.createURI(NAMESPACE, "ST_Dimension") static
ST_DISTANCE
final URI ST_DISTANCE =factory.createURI(NAMESPACE, "ST_Distance") static
ST_DISTANCE3D
final URI ST_DISTANCE3D =factory.createURI(NAMESPACE, "ST_Distance3D") static
Referenced by Distance3D.getURI().
ST_DISTANCESPHERE
final URI ST_DISTANCESPHERE =factory.createURI(NAMESPACE, "ST_DistanceSphere") static
Referenced by DistanceSphere.getURI().
ST_DWITHIN
final URI ST_DWITHIN =factory.createURI(NAMESPACE, "ST_DWithin") static
ST_DWITHIN3D
final URI ST_DWITHIN3D =factory.createURI(NAMESPACE, "ST_3DDWithin") static
ST_ENDPOINT
final URI ST_ENDPOINT =factory.createURI(NAMESPACE, "ST_EndPoint") static
Referenced by EndPoint.getURI().
ST_EPSGTOSRID
final URI ST_EPSGTOSRID =factory.createURI(NAMESPACE, "ST_EPSGToSRID") static
st_epsgToSRID
final URI st_epsgToSRID =factory.createURI(NAMESPACE, "ST_EPSGToSRID") static
ST_EQUALS
final URI ST_EQUALS =factory.createURI(NAMESPACE, "ST_Equals") static
st_equals
final URI st_equals =factory.createURI(NAMESPACE, "ST_Equals") static
Referenced by Equals.getURI().
ST_EQUALSNORM
final URI ST_EQUALSNORM =factory.createURI(NAMESPACE, "ST_EqualsNorm") static
st_equalsNorm
final URI st_equalsNorm =factory.createURI(NAMESPACE, "ST_EqualNorm") static
Referenced by EqualsNorm.getURI().
ST_EQUALSRS
final URI ST_EQUALSRS =factory.createURI(NAMESPACE, "ST_EqualSRS") static
st_equalSRS
final URI st_equalSRS =factory.createURI(NAMESPACE, "ST_EqualSRS") static
Referenced by EqualSRS.getURI().
ST_EQUALSTOPO
final URI ST_EQUALSTOPO =factory.createURI(NAMESPACE, "ST_EqualsTopo") static
st_equalsTopo
final URI st_equalsTopo =factory.createURI(NAMESPACE, "ST_EqualTopo") static
Referenced by EqualsTopo.getURI().
st_exteriorRing
final URI st_exteriorRing =factory.createURI(NAMESPACE, "ST_ExteriorRing") static
Referenced by ExteriorRing.getURI().
ST_FILTERBYM
final URI ST_FILTERBYM =factory.createURI(NAMESPACE, "ST_FilterByM") static
st_filterByM
final URI st_filterByM =factory.createURI(NAMESPACE, "ST_FilterByM") static
ST_FILTERBYT
final URI ST_FILTERBYT =factory.createURI(NAMESPACE, "ST_FilterByT") static
st_filterByT
final URI st_filterByT =factory.createURI(NAMESPACE, "ST_FilterByT") static
st_flip
final URI st_flip =factory.createURI(NAMESPACE, "ST_Flip") static
ST_FLIPCOORDINATES
final URI ST_FLIPCOORDINATES =factory.createURI(NAMESPACE, "ST_FlipCoordinates") static
st_flipCoordinates
final URI st_flipCoordinates =factory.createURI(NAMESPACE, "ST_FlipCoordinates") static
Referenced by FlipCoordinates.getURI().
ST_flowdirection
final URI ST_flowdirection =factory.createURI(NAMESPACE, "ST_FlowDirection") static
st_force2d
final URI st_force2d =factory.createURI(NAMESPACE, "ST_Force2D") static
Referenced by Force2D.getURI().
st_force3d
final URI st_force3d =factory.createURI(NAMESPACE, "ST_Force3D") static
Referenced by Force3D.getURI().
st_force3dm
final URI st_force3dm =factory.createURI(NAMESPACE, "ST_Force3DM") static
Referenced by Force3DM.getURI().
st_force3dz
final URI st_force3dz =factory.createURI(NAMESPACE, "ST_Force3D") static
st_force4d
final URI st_force4d =factory.createURI(NAMESPACE, "ST_Force4D") static
Referenced by Force4D.getURI().
st_forceCollection
final URI st_forceCollection =factory.createURI(NAMESPACE, "ST_ForceCollection") static
Referenced by ForceCollection.getURI().
st_forceCurve
final URI st_forceCurve =factory.createURI(NAMESPACE, "ST_ForceCurve") static
st_forceLHR
final URI st_forceLHR =factory.createURI(NAMESPACE, "ST_ForceLHR") static
st_forcePolygonCCW
final URI st_forcePolygonCCW =factory.createURI(NAMESPACE, "ST_ForcePolygonCCW") static
Referenced by ForcePolygonCCW.getURI().
st_forcePolygonCW
final URI st_forcePolygonCW =factory.createURI(NAMESPACE, "ST_ForcePolygonCW") static
Referenced by ForcePolygonCW.getURI().
st_forceSFS
final URI st_forceSFS =factory.createURI(NAMESPACE, "ST_ForceSFS") static
st_frechetDistance
final URI st_frechetDistance =factory.createURI(NAMESPACE, "ST_FrechetDistance") static
st_generatePoints
final URI st_generatePoints =factory.createURI(NAMESPACE, "ST_GeneratePoints") static
st_geohash
final URI st_geohash =factory.createURI(NAMESPACE, "ST_AsGeoHash") static
st_geometricMedian
final URI st_geometricMedian =factory.createURI(NAMESPACE, "ST_GeometricMedian") static
Referenced by GeometricMedian.getURI().
st_geometryN
final URI st_geometryN =factory.createURI(NAMESPACE, "ST_GeometryN") static
Referenced by GeometryN.getURI().
st_geometryType
final URI st_geometryType =factory.createURI(NAMESPACE, "ST_GeometryType") static
Referenced by GeometryType.getURI().
st_geomFromGeoHash
final URI st_geomFromGeoHash =factory.createURI(NAMESPACE, "ST_GeomFromGeoHash") static
Referenced by GeomFromGeoHash.getURI().
st_geomFromGeoJSON
final URI st_geomFromGeoJSON =factory.createURI(NAMESPACE, "ST_GeomFromGeoJSON") static
Referenced by GeomFromGeoJSON.getURI().
st_geomFromGML
final URI st_geomFromGML =factory.createURI(NAMESPACE, "ST_GeomFromGML") static
st_geomFromKML
final URI st_geomFromKML =factory.createURI(NAMESPACE, "ST_GeomFromKML") static
st_geomFromText
final URI st_geomFromText =factory.createURI(NAMESPACE, "ST_GeomFromText") static
Referenced by GeomFromText.getURI().
st_geomFromWKB
final URI st_geomFromWKB =factory.createURI(NAMESPACE, "ST_GeomFromWKB") static
Referenced by GeomFromWKB.getURI().
st_gmlToSQL
final URI st_gmlToSQL =factory.createURI(NAMESPACE, "ST_GeomFromGML") static
ST_hasHorizontalCRS
final URI ST_hasHorizontalCRS =factory.createURI(NAMESPACE, "ST_HasHorizontalCRS") static
Referenced by HasHorizontalCRS.getURI().
st_hasNoBand
final URI st_hasNoBand =factory.createURI(NAMESPACE, "ST_HasNoBand") static
Referenced by HasNoBand.getURI().
st_hasRepeatedPoints
final URI st_hasRepeatedPoints =factory.createURI(NAMESPACE, "ST_HasRepeatedPoints") static
Referenced by HasRepeatedPoints.getURI().
st_hausdorffDistance
final URI st_hausdorffDistance =factory.createURI(NAMESPACE, "ST_HausdorffDistance") static
Referenced by HausdorffDistance.getURI().
st_height
final URI st_height =factory.createURI(NAMESPACE, "ST_Height") static
Referenced by Height.getURI().
st_hillshade
final URI st_hillshade =factory.createURI(NAMESPACE, "ST_Hillshade") static
st_histogram
final URI st_histogram = factory.createURI(NAMESPACE,"ST_Histogram") static
st_interiorRingN
final URI st_interiorRingN =factory.createURI(NAMESPACE, "ST_InteriorRingN") static
Referenced by InteriorRingN.getURI().
st_interpolatePoint
final URI st_interpolatePoint =factory.createURI(NAMESPACE, "ST_InterpolatePoint") static
st_intersectionPercentage
final URI st_intersectionPercentage =factory.createURI(NAMESPACE, "ST_IntersectionPercentage") static
Referenced by IntersectionPercentage.getURI().
st_is3D
final URI st_is3D =factory.createURI(NAMESPACE, "ST_Is3D") static
Referenced by Is3D.getURI().
st_isClosed
final URI st_isClosed =factory.createURI(NAMESPACE, "ST_IsClosed") static
Referenced by IsClosed.getURI().
st_isCollection
final URI st_isCollection =factory.createURI(NAMESPACE, "ST_IsCollection") static
Referenced by IsCollection.getURI().
st_isConvex
final URI st_isConvex =factory.createURI(NAMESPACE, "ST_IsConvex") static
Referenced by IsConvex.getURI().
st_isEmpty
final URI st_isEmpty =factory.createURI(NAMESPACE, "ST_IsEmpty") static
Referenced by IsEmpty.getURI().
st_isGrayscale
final URI st_isGrayscale =factory.createURI(NAMESPACE, "ST_IsGrayscale") static
Referenced by IsGrayscale.getURI().
st_isIndexed
final URI st_isIndexed =factory.createURI(NAMESPACE, "ST_IsIndexed") static
Referenced by IsIndexed.getURI().
st_isLocationOnEdge
final URI st_isLocationOnEdge =factory.createURI(NAMESPACE, "ST_IsLocationOnEdge") static
Referenced by IsLocationOnEdge.getURI().
st_isMeasured
final URI st_isMeasured =factory.createURI(NAMESPACE, "ST_IsMeasured") static
Referenced by IsMeasured.getURI().
st_isMorePrecise
final URI st_isMorePrecise =factory.createURI(NAMESPACE, "ST_IsMorePrecise") static
Referenced by IsMorePrecise.getURI().
st_isNodingValid
final URI st_isNodingValid =factory.createURI(NAMESPACE, "ST_IsNodingValid") static
Referenced by IsNodingValid.getURI().
st_isPointInRing
final URI st_isPointInRing =factory.createURI(NAMESPACE, "ST_IsPointInRing") static
Referenced by IsPointInRing.getURI().
st_isPointOnLine
final URI st_isPointOnLine =factory.createURI(NAMESPACE, "ST_IsPointOnLine") static
Referenced by IsPointOnLine.getURI().
st_isPolygonCCW
final URI st_isPolygonCCW =factory.createURI(NAMESPACE, "ST_IsPolygonCCW") static
Referenced by IsPolygonCCW.getURI().
st_isPolygonCW
final URI st_isPolygonCW =factory.createURI(NAMESPACE, "ST_IsPolygonCW") static
Referenced by IsPolygonCW.getURI().
st_isRectangle
final URI st_isRectangle =factory.createURI(NAMESPACE, "ST_IsRectangle") static
Referenced by IsRectangle.getURI().
st_isRing
final URI st_isRing =factory.createURI(NAMESPACE, "ST_IsRing") static
Referenced by IsRing.getURI().
st_isSimple
final URI st_isSimple =factory.createURI(NAMESPACE, "ST_IsSimpleFF") static
Referenced by IsSimple.getURI().
st_isTiled
final URI st_isTiled =factory.createURI(NAMESPACE, "ST_IsTiled") static
Referenced by IsTiled.getURI().
st_isTranslucent
final URI st_isTranslucent =factory.createURI(NAMESPACE, "ST_IsTranslucent") static
Referenced by IsTranslucent.getURI().
st_isValid
final URI st_isValid =factory.createURI(NAMESPACE, "ST_IsValidFF") static
Referenced by IsValid.getURI().
st_isValidDetail
final URI st_isValidDetail =factory.createURI(NAMESPACE, "ST_IsValidDetail") static
st_isValidReason
final URI st_isValidReason =factory.createURI(NAMESPACE, "ST_IsValidReason") static
st_isValidTrajectory
final URI st_isValidTrajectory =factory.createURI(NAMESPACE, "ST_IsValidTrajectory") static
Referenced by IsValidTrajectory.getURI().
st_Length
final URI st_Length =factory.createURI(NAMESPACE, "ST_Length") static
Referenced by Length.getURI().
st_Length2D
final URI st_Length2D =factory.createURI(NAMESPACE, "ST_Length") static
st_Length3D
final URI st_Length3D =factory.createURI(NAMESPACE, "ST_Length3D") static
Referenced by Length3D.getURI().
st_LengthToPoint
final URI st_LengthToPoint =factory.createURI(NAMESPACE, "ST_LengthToPoint") static
Referenced by LengthToPoint.getURI().
st_lineCrossingDirection
final URI st_lineCrossingDirection =factory.createURI(NAMESPACE, "ST_LineCrossingDirection") static
st_lineFromEncodedPolyline
final URI st_lineFromEncodedPolyline =factory.createURI(NAMESPACE, "ST_LineFromEncodedPolyline") static
Referenced by LineFromEncodedPolyline.getURI().
st_lineFromMultiPoint
final URI st_lineFromMultiPoint =factory.createURI(NAMESPACE, "ST_LineFromMultiPoint") static
Referenced by LineFromMultiPoint.getURI().
st_lineFromText
final URI st_lineFromText =factory.createURI(NAMESPACE, "ST_LineFromText") static
Referenced by LineFromText.getURI().
st_lineFromWKB
final URI st_lineFromWKB =factory.createURI(NAMESPACE, "ST_LineFromWKB") static
Referenced by LineFromWKB.getURI().
st_lineFromWKT
final URI st_lineFromWKT =factory.createURI(NAMESPACE, "ST_LineFromText") static
st_lineInterpolatePoint
final URI st_lineInterpolatePoint =factory.createURI(NAMESPACE, "ST_LineInterpolatePoint") static
Referenced by LineInterpolatePoint.getURI().
st_lineInterpolatePoints
final URI st_lineInterpolatePoints =factory.createURI(NAMESPACE, "ST_LineInterpolatePoints") static
st_lineLength3D
final URI st_lineLength3D =factory.createURI(NAMESPACE, "ST_LineLength3D") static
Referenced by LineLength3D.getURI().
st_lineLocatePoint
final URI st_lineLocatePoint =factory.createURI(NAMESPACE, "ST_LineLocatePoint") static
st_lineMerge
final URI st_lineMerge =factory.createURI(NAMESPACE, "ST_LineMerge") static
Referenced by LineMerge.getURI().
st_lineSelfIntersectionPoint
final URI st_lineSelfIntersectionPoint =factory.createURI(NAMESPACE, "ST_LineSelfIntersectionPoint") static
Referenced by LineSelfIntersectionPoint.getURI().
st_lineSubstring
final URI st_lineSubstring =factory.createURI(NAMESPACE, "ST_LineSubstring") static
st_lineToCurve
final URI st_lineToCurve =factory.createURI(NAMESPACE, "ST_LineToCurve") static
st_locateAlong
final URI st_locateAlong =factory.createURI(NAMESPACE, "ST_LocateAlong") static
st_locateBetween
final URI st_locateBetween =factory.createURI(NAMESPACE, "ST_LocateBetween") static
st_locateBetweenElevations
final URI st_locateBetweenElevations =factory.createURI(NAMESPACE, "ST_LocateBetweenElevations") static
st_longestLine
final URI st_longestLine =factory.createURI(NAMESPACE, "ST_LongestLine") static
Referenced by LongestLine.getURI().
ST_LONGESTLINE3D
final URI ST_LONGESTLINE3D =factory.createURI(NAMESPACE, "ST_LongestLine3D") static
st_m
final URI st_m =factory.createURI(NAMESPACE, "ST_M") static
Referenced by M.getURI().
st_makeBox2D
final URI st_makeBox2D =factory.createURI(NAMESPACE, "ST_MakeBox2D") static
Referenced by MakeBox2D.getURI().
st_makeBox3D
final URI st_makeBox3D =factory.createURI(NAMESPACE, "ST_MakeBox3D") static
Referenced by MakeBox3D.getURI().
st_makeCircle
final URI st_makeCircle =factory.createURI(NAMESPACE, "ST_MakeCircle") static
st_makeEllipse
final URI st_makeEllipse =factory.createURI(NAMESPACE, "ST_MakeEllipse") static
st_makeEmptyCoverage
final URI st_makeEmptyCoverage =factory.createURI(NAMESPACE, "ST_MakeEmptyCoverage") static
st_makeEmptyRaster
final URI st_makeEmptyRaster =factory.createURI(NAMESPACE, "ST_MakeEmptyRaster") static
st_makeEnvelope
final URI st_makeEnvelope =factory.createURI(NAMESPACE, "ST_MakeEnvelope") static
Referenced by MakeEnvelope.getURI().
st_makeLine
final URI st_makeLine =factory.createURI(NAMESPACE, "ST_MakeLine") static
Referenced by MakeLine.getURI().
st_makePoint
final URI st_makePoint =factory.createURI(NAMESPACE, "ST_MakePoint") static
Referenced by MakePoint.getURI().
st_makePointM
final URI st_makePointM =factory.createURI(NAMESPACE, "ST_MakePointM") static
st_makePolygon
final URI st_makePolygon =factory.createURI(NAMESPACE, "ST_MakePolygon") static
Referenced by MakePolygon.getURI().
st_makeValid
final URI st_makeValid =factory.createURI(NAMESPACE, "ST_MakeValid") static
st_maxDistance
final URI st_maxDistance =factory.createURI(NAMESPACE, "ST_MaxDistance") static
Referenced by MaxDistance.getURI().
ST_MAXDISTANCE3D
final URI ST_MAXDISTANCE3D =factory.createURI(NAMESPACE, "ST_MaxDistance3D") static
st_maxDistance3D
final URI st_maxDistance3D =factory.createURI(NAMESPACE, "ST_MaxDistance3D") static
Referenced by MaxDistance3D.getURI().
st_memsize
final URI st_memsize =factory.createURI(NAMESPACE, "ST_MemSize") static
st_minConvexHull
final URI st_minConvexHull =factory.createURI(NAMESPACE, "ST_MinConvexHull") static
st_minimumBoundingCircle
final URI st_minimumBoundingCircle =factory.createURI(NAMESPACE, "ST_MinimumBoundingCircle") static
Referenced by MinimumBoundingCircle.getURI().
st_minimumBoundingCircleCenter
final URI st_minimumBoundingCircleCenter =factory.createURI(NAMESPACE, "ST_MinimumBoundingCircleCenter") static
Referenced by MinimumBoundingCircleCenter.getURI().
st_minimumBoundingRadius
final URI st_minimumBoundingRadius =factory.createURI(NAMESPACE, "ST_MinimumBoundingRadius") static
Referenced by MinimumBoundingRadius.getURI().
st_minimumClearance
final URI st_minimumClearance =factory.createURI(NAMESPACE, "ST_MinimumClearance") static
Referenced by MinimumClearance.getURI().
st_minimumClearanceLine
final URI st_minimumClearanceLine =factory.createURI(NAMESPACE, "ST_MinimumClearanceLine") static
Referenced by MinimumClearanceLine.getURI().
st_minimumDiameter
final URI st_minimumDiameter =factory.createURI(NAMESPACE, "ST_MinimumDiameter") static
Referenced by MinimumDiameter.getURI().
st_minimumDiameterLine
final URI st_minimumDiameterLine =factory.createURI(NAMESPACE, "ST_MinimumDiameterLine") static
Referenced by MinimumDiameterLine.getURI().
st_minimumRectangle
final URI st_minimumRectangle =factory.createURI(NAMESPACE, "ST_MinimumRectangle") static
Referenced by MinimumRectangle.getURI().
st_minTileX
final URI st_minTileX =factory.createURI(NAMESPACE, "ST_MinTileX") static
Referenced by MinTileX.getURI().
st_minTileY
final URI st_minTileY =factory.createURI(NAMESPACE, "ST_MinTileY") static
Referenced by MinTileY.getURI().
st_mirror
final URI st_mirror =factory.createURI(NAMESPACE, "ST_Mirror") static
st_mLineFromText
final URI st_mLineFromText =factory.createURI(NAMESPACE, "ST_MLineFromText") static
Referenced by MLineFromText.getURI().
st_mMax
final URI st_mMax =factory.createURI(NAMESPACE, "ST_MMax") static
Referenced by MMax.getURI().
st_mMin
final URI st_mMin =factory.createURI(NAMESPACE, "ST_MMin") static
Referenced by MMin.getURI().
st_mPointFromText
final URI st_mPointFromText =factory.createURI(NAMESPACE, "ST_MPointFromText") static
Referenced by MPointFromText.getURI().
st_mPolyFromText
final URI st_mPolyFromText =factory.createURI(NAMESPACE, "ST_MPolyFromText") static
st_multi
final URI st_multi =factory.createURI(NAMESPACE, "ST_Multi") static
Referenced by Multi.getURI().
st_multiplyz
final URI st_multiplyz =factory.createURI(NAMESPACE, "ST_MultiplyZ") static
Referenced by MultiplyZ.getURI().
st_nDims
final URI st_nDims =factory.createURI(NAMESPACE, "ST_NDims") static
Referenced by NDims.getURI().
st_nearestValue
final URI st_nearestValue =factory.createURI(NAMESPACE, "ST_NearestValue") static
st_node
final URI st_node =factory.createURI(NAMESPACE, "ST_Node") static
st_normalize
final URI st_normalize =factory.createURI(NAMESPACE, "ST_Normalize") static
Referenced by Normalize.getURI().
st_nPoints
final URI st_nPoints =factory.createURI(NAMESPACE, "ST_NumPoints") static
st_nRings
final URI st_nRings =factory.createURI(NAMESPACE, "ST_NRings") static
st_numBands
final URI st_numBands =factory.createURI(NAMESPACE, "ST_NumBands") static
Referenced by NumBands.getURI().
st_numGeometries
final URI st_numGeometries =factory.createURI(NAMESPACE, "ST_NumGeometries") static
Referenced by NumGeometries.getURI().
st_numInteriorRings
final URI st_numInteriorRings =factory.createURI(NAMESPACE, "ST_NumInteriorRings") static
Referenced by NumInteriorRings.getURI().
st_numPatches
final URI st_numPatches =factory.createURI(NAMESPACE, "ST_NumPatches") static
Referenced by NumPatches.getURI().
st_numPoints
final URI st_numPoints =factory.createURI(NAMESPACE, "ST_NumPoints") static
Referenced by NumPoints.getURI().
st_numXTiles
final URI st_numXTiles =factory.createURI(NAMESPACE, "ST_NumXTiles") static
Referenced by NumXTiles.getURI().
st_numYTiles
final URI st_numYTiles =factory.createURI(NAMESPACE, "ST_NumYTiles") static
Referenced by NumYTiles.getURI().
st_octogonalEnvelope
final URI st_octogonalEnvelope =factory.createURI(NAMESPACE, "ST_OctogonalEnvelope") static
Referenced by OctogonalEnvelope.getURI().
st_offsetCurve
final URI st_offsetCurve =factory.createURI(NAMESPACE, "ST_OffsetCurve") static
st_orderingEquals
final URI st_orderingEquals =factory.createURI(NAMESPACE, "ST_OrderingEquals") static
Referenced by OrderingEquals.getURI().
st_orientation
final URI st_orientation =factory.createURI(NAMESPACE, "ST_Orientation") static
Referenced by Orientation.getURI().
st_osmlink
final URI st_osmlink =factory.createURI(NAMESPACE, "ST_AsOSMLink") static
Referenced by AsOSMLink.getURI().
st_partOfGeometryAfter
final URI st_partOfGeometryAfter =factory.createURI(NAMESPACE, "ST_PartOfGeometryAfter") static
st_partOfGeometryBefore
final URI st_partOfGeometryBefore =factory.createURI(NAMESPACE, "ST_PartOfGeometryBefore") static
st_patchN
final URI st_patchN =factory.createURI(NAMESPACE, "ST_PatchN") static
st_perimeter
final URI st_perimeter =factory.createURI(NAMESPACE, "ST_Perimeter") static
Referenced by Perimeter.getURI().
st_perimeter2D
final URI st_perimeter2D =factory.createURI(NAMESPACE, "ST_Perimeter") static
st_perimeter3D
final URI st_perimeter3D =factory.createURI(NAMESPACE, "ST_Perimeter3D") static
Referenced by Perimeter3D.getURI().
st_pixelAsCentroid
final URI st_pixelAsCentroid =factory.createURI(NAMESPACE, "ST_PixelAsCentroid") static
st_pixelAsCentroids
final URI st_pixelAsCentroids =factory.createURI(NAMESPACE, "ST_PixelAsCentroids") static
st_pixelAsPoint
final URI st_pixelAsPoint =factory.createURI(NAMESPACE, "ST_PixelAsPoint") static
st_pixelAsPoints
final URI st_pixelAsPoints =factory.createURI(NAMESPACE, "ST_PixelAsPoints") static
st_pixelAsPolygon
final URI st_pixelAsPolygon =factory.createURI(NAMESPACE, "ST_PixelAsPolygon") static
st_pixelAsPolygons
final URI st_pixelAsPolygons =factory.createURI(NAMESPACE, "ST_PixelAsPolygons") static
st_pixelHeight
final URI st_pixelHeight =factory.createURI(NAMESPACE, "ST_PixelHeight") static
st_pixelOfValue
final URI st_pixelOfValue =factory.createURI(NAMESPACE, "ST_PixelOfValue") static
st_pixelWidth
final URI st_pixelWidth =factory.createURI(NAMESPACE, "ST_PixelWidth") static
st_pointFromGeoHash
final URI st_pointFromGeoHash =factory.createURI(NAMESPACE, "ST_PointFromGeoHash") static
Referenced by PointFromGeoHash.getURI().
st_pointFromText
final URI st_pointFromText =factory.createURI(NAMESPACE, "ST_PointFromText") static
Referenced by PointFromText.getURI().
st_pointFromWKB
final URI st_pointFromWKB =factory.createURI(NAMESPACE, "ST_PointFromWKB") static
Referenced by PointFromWKB.getURI().
st_pointInsideCircle
final URI st_pointInsideCircle =factory.createURI(NAMESPACE, "ST_PointInsideCircle") static
st_pointN
final URI st_pointN =factory.createURI(NAMESPACE, "ST_PointN") static
Referenced by PointN.getURI().
st_pointOnSurface
final URI st_pointOnSurface =factory.createURI(NAMESPACE, "ST_PointOnSurface") static
Referenced by PointOnSurface.getURI().
st_points
final URI st_points =factory.createURI(NAMESPACE, "ST_Points") static
Referenced by Points.getURI().
st_polygon
final URI st_polygon =factory.createURI(NAMESPACE, "ST_Polygon") static
Referenced by Polygon.getURI().
st_polygonFromText
final URI st_polygonFromText =factory.createURI(NAMESPACE, "ST_PolygonFromText") static
Referenced by PolygonFromText.getURI().
st_polygonFromWKB
final URI st_polygonFromWKB =factory.createURI(NAMESPACE, "ST_PolygonFromWKB") static
Referenced by PolygonFromWKB.getURI().
st_polygonize
final URI st_polygonize =factory.createURI(NAMESPACE, "ST_Polygonize") static
st_precisionReducer
final URI st_precisionReducer =factory.createURI(NAMESPACE, "ST_PrecisionReducer") static
Referenced by PrecisionReducer.getURI().
st_rast_Contains
final URI st_rast_Contains =factory.createURI(NAMESPACE, "ST_Contains") static
st_rast_CoveredBy
final URI st_rast_CoveredBy =factory.createURI(NAMESPACE, "ST_CoveredBy") static
Referenced by CoveredBy.getURI().
st_rast_Covers
final URI st_rast_Covers =factory.createURI(NAMESPACE, "ST_Covers") static
st_rast_Crosses
final URI st_rast_Crosses =factory.createURI(NAMESPACE, "ST_Crosses") static
Referenced by Crosses.getURI().
st_rast_Disjoint
final URI st_rast_Disjoint =factory.createURI(NAMESPACE, "ST_Disjoint") static
Referenced by Disjoint.getURI().
st_rast_Intersection
final URI st_rast_Intersection =factory.createURI(NAMESPACE, "ST_Intersection") static
Referenced by Intersection.getURI().
st_rast_Intersects
final URI st_rast_Intersects =factory.createURI(NAMESPACE, "ST_Intersects") static
Referenced by Intersects.getURI().
st_rast_isEmpty
final URI st_rast_isEmpty =factory.createURI(NAMESPACE, "ST_IsEmpty") static
st_rast_Overlaps
final URI st_rast_Overlaps =factory.createURI(NAMESPACE, "ST_Overlaps") static
Referenced by Overlaps.getURI().
st_rast_srid
final URI st_rast_srid =factory.createURI(NAMESPACE, "ST_SRID") static
st_rast_Touches
final URI st_rast_Touches =factory.createURI(NAMESPACE, "ST_Touches") static
Referenced by Touches.getURI().
st_rast_Within
final URI st_rast_Within =factory.createURI(NAMESPACE, "ST_Within") static
Referenced by Within.getURI().
st_rasterToWorldCoord
final URI st_rasterToWorldCoord =factory.createURI(NAMESPACE, "ST_RasterToWorldCoord") static
Referenced by RasterToWorldCoord.getURI().
st_rasterToWorldCoordX
final URI st_rasterToWorldCoordX =factory.createURI(NAMESPACE, "ST_RasterToWorldCoordX") static
Referenced by RasterToWorldCoordX.getURI().
st_rasterToWorldCoordY
final URI st_rasterToWorldCoordY =factory.createURI(NAMESPACE, "ST_RasterToWorldCoordY") static
Referenced by RasterToWorldCoordY.getURI().
st_rastFromHexWKB
final URI st_rastFromHexWKB =factory.createURI(NAMESPACE, "ST_RastFromHexWKB") static
Referenced by RastFromHexWKB.getURI().
st_rastFromWKB
final URI st_rastFromWKB =factory.createURI(NAMESPACE, "ST_RastFromWKB") static
Referenced by RastFromWKB.getURI().
st_reflect
final URI st_reflect =factory.createURI(NAMESPACE, "ST_Reflect") static
Referenced by Reflect.getURI().
st_relate
final URI st_relate =factory.createURI(NAMESPACE, "ST_Relate") static
Referenced by Relate.getURI().
st_relateMatch
final URI st_relateMatch =factory.createURI(NAMESPACE, "ST_RelateMatch") static
st_removePoint
final URI st_removePoint =factory.createURI(NAMESPACE, "ST_RemovePoint") static
Referenced by RemovePoint.getURI().
st_removePoints
final URI st_removePoints =factory.createURI(NAMESPACE, "ST_RemovePoints") static
st_removeRepeatedPoints
final URI st_removeRepeatedPoints =factory.createURI(NAMESPACE, "ST_RemoveRepeatedPoints") static
Referenced by RemoveRepeatedPoints.getURI().
st_resample
final URI st_resample =factory.createURI(NAMESPACE, "ST_Resample") static
st_rescale
final URI st_rescale =factory.createURI(NAMESPACE, "ST_Rescale") static
st_resize
final URI st_resize =factory.createURI(NAMESPACE, "ST_Resize") static
st_reskew
final URI st_reskew =factory.createURI(NAMESPACE, "ST_Reskew") static
st_retile
final URI st_retile =factory.createURI(NAMESPACE, "ST_Retile") static
st_reverse
final URI st_reverse =factory.createURI(NAMESPACE, "ST_Reverse") static
Referenced by Reverse.getURI().
st_rotate
final URI st_rotate =factory.createURI(NAMESPACE, "ST_Rotate") static
Referenced by Rotate.getURI().
st_rotateX
final URI st_rotateX =factory.createURI(NAMESPACE, "ST_RotateX") static
Referenced by RotateX.getURI().
st_rotateY
final URI st_rotateY =factory.createURI(NAMESPACE, "ST_RotateY") static
st_rotateZ
final URI st_rotateZ =factory.createURI(NAMESPACE, "ST_RotateZ") static
st_rotation
final URI st_rotation =factory.createURI(NAMESPACE, "ST_Rotation") static
st_roughness
final URI st_roughness =factory.createURI(NAMESPACE, "ST_Roughness") static
st_scale
final URI st_scale =factory.createURI(NAMESPACE, "ST_Scale") static
st_scaleX
final URI st_scaleX =factory.createURI(NAMESPACE, "ST_ScaleX") static
Referenced by ScaleX.getURI().
st_scaleY
final URI st_scaleY =factory.createURI(NAMESPACE, "ST_ScaleY") static
Referenced by ScaleY.getURI().
st_segmentize
final URI st_segmentize =factory.createURI(NAMESPACE, "ST_Segmentize") static
Referenced by Segmentize.getURI().
st_setGeoReference
final URI st_setGeoReference =factory.createURI(NAMESPACE, "ST_SetGeoReference") static
st_setPoint
final URI st_setPoint =factory.createURI(NAMESPACE, "ST_SetPoint") static
Referenced by SetPoint.getURI().
st_setRotation
final URI st_setRotation =factory.createURI(NAMESPACE, "ST_SetRotation") static
Referenced by SetRotation.getURI().
st_setScale
final URI st_setScale =factory.createURI(NAMESPACE, "ST_SetScale") static
Referenced by SetScale.getURI().
st_setSkew
final URI st_setSkew =factory.createURI(NAMESPACE, "ST_SetSkew") static
Referenced by SetSkew.getURI().
st_setSRID
final URI st_setSRID =factory.createURI(NAMESPACE, "ST_SetSRID") static
Referenced by SetSRID.getURI().
st_setUpperLeft
final URI st_setUpperLeft =factory.createURI(NAMESPACE, "ST_SetUpperLeft") static
Referenced by SetUpperLeft.getURI().
st_sharedPaths
final URI st_sharedPaths =factory.createURI(NAMESPACE, "ST_SharedPaths") static
Referenced by SharedPaths.getURI().
st_shearTransformation
final URI st_shearTransformation =factory.createURI(NAMESPACE, "ST_ShearTransformation") static
st_shift
final URI st_shift =factory.createURI(NAMESPACE, "ST_Shift") static
st_shiftLongitude
final URI st_shiftLongitude =factory.createURI(NAMESPACE, "ST_ShiftLongitude") static
Referenced by ShiftLongitude.getURI().
st_shortestLine
final URI st_shortestLine =factory.createURI(NAMESPACE, "ST_ShortestLine") static
Referenced by ShortestLine.getURI().
ST_SHORTESTLINE3D
final URI ST_SHORTESTLINE3D =factory.createURI(NAMESPACE, "ST_ShortestLine3D") static
st_shortestLine3D
final URI st_shortestLine3D =factory.createURI(NAMESPACE, "ST_ShortestLine3D") static
Referenced by ShortestLine3D.getURI().
st_simplify
final URI st_simplify =factory.createURI(NAMESPACE, "ST_Simplify") static
st_simplifyPreserveTopology
final URI st_simplifyPreserveTopology =factory.createURI(NAMESPACE, "ST_SimplifyPreserveTopology") static
st_simplifyVW
final URI st_simplifyVW =factory.createURI(NAMESPACE, "ST_SimplifyVW") static
st_skewX
final URI st_skewX =factory.createURI(NAMESPACE, "ST_SkewX") static
Referenced by SkewX.getURI().
st_skewY
final URI st_skewY =factory.createURI(NAMESPACE, "ST_SkewY") static
Referenced by SkewY.getURI().
st_slope
final URI st_slope =factory.createURI(NAMESPACE, "ST_Slope") static
st_snap
final URI st_snap =factory.createURI(NAMESPACE, "ST_Snap") static
Referenced by Snap.getURI().
st_split
final URI st_split =factory.createURI(NAMESPACE, "ST_Split") static
st_srid
final URI st_srid =factory.createURI(NAMESPACE, "ST_GetSRIDFF") static
st_sridToEPSG
final URI st_sridToEPSG =factory.createURI(NAMESPACE, "ST_SRIDToEPSG") static
st_startPoint
final URI st_startPoint =factory.createURI(NAMESPACE, "ST_StartPoint") static
Referenced by StartPoint.getURI().
st_straightSkeleton
final URI st_straightSkeleton =factory.createURI(NAMESPACE, "ST_StraightSkeleton") static
st_summary
final URI st_summary =factory.createURI(NAMESPACE, "ST_Summary") static
st_swapOrdinates
final URI st_swapOrdinates =factory.createURI(NAMESPACE, "ST_SwapOrdinates") static
Referenced by SwapOrdinates.getURI().
st_symDifference
final URI st_symDifference =factory.createURI(NAMESPACE, "ST_SymDifference") static
st_t
final URI st_t =factory.createURI(NAMESPACE, "ST_T") static
st_tesselate
final URI st_tesselate =factory.createURI(NAMESPACE, "ST_Tesselate") static
st_tileGridXOffset
final URI st_tileGridXOffset = factory.createURI(NAMESPACE, "ST_TileGridXOffset") static
Referenced by TileGridXOffset.getURI().
st_tileGridYOffset
final URI st_tileGridYOffset = factory.createURI(NAMESPACE, "ST_TileGridYOffset") static
Referenced by TileGridYOffset.getURI().
st_tileHeight
final URI st_tileHeight = factory.createURI(NAMESPACE, "ST_TileHeight") static
Referenced by TileHeight.getURI().
st_tileWidth
final URI st_tileWidth = factory.createURI(NAMESPACE, "ST_TileWidth") static
Referenced by TileWidth.getURI().
st_tMax
final URI st_tMax =factory.createURI(NAMESPACE, "ST_TMax") static
st_tMin
final URI st_tMin =factory.createURI(NAMESPACE, "ST_TMin") static
st_tpi
final URI st_tpi =factory.createURI(NAMESPACE, "ST_TPI") static
st_transform
final URI st_transform =factory.createURI(NAMESPACE, "ST_Transform") static
Referenced by Transform.getURI().
st_translate
final URI st_translate =factory.createURI(NAMESPACE, "ST_Translate") static
Referenced by Translate.getURI().
st_transscale
final URI st_transscale =factory.createURI(NAMESPACE, "ST_TransScale") static
Referenced by TransScale.getURI().
st_tri
final URI st_tri =factory.createURI(NAMESPACE, "ST_TRI") static
st_unaryUnion
final URI st_unaryUnion =factory.createURI(NAMESPACE, "ST_UnaryUnion") static
st_union
final URI st_union =factory.createURI(NAMESPACE, "ST_Union") static
st_upperLeftX
final URI st_upperLeftX =factory.createURI(NAMESPACE, "ST_UpperLeftX") static
Referenced by UpperLeftX.getURI().
st_upperLeftY
final URI st_upperLeftY =factory.createURI(NAMESPACE, "ST_UpperLeftY") static
Referenced by UpperLeftY.getURI().
st_vectorize
final URI st_vectorize =factory.createURI(NAMESPACE, "ST_Vectorize") static
st_voronoiLines
final URI st_voronoiLines =factory.createURI(NAMESPACE, "ST_VoronoiLines") static
st_voronoiPolygons
final URI st_voronoiPolygons =factory.createURI(NAMESPACE, "ST_VoronoiPolygons") static
st_width
final URI st_width =factory.createURI(NAMESPACE, "ST_Width") static
Referenced by Width.getURI().
st_wkbToSQL
final URI st_wkbToSQL =factory.createURI(NAMESPACE, "ST_GeomFromWKB") static
st_wktToSQL
final URI st_wktToSQL =factory.createURI(NAMESPACE, "ST_GeomFromText") static
st_worldToRasterCoord
final URI st_worldToRasterCoord =factory.createURI(NAMESPACE, "ST_WorldToRasterCoord") static
Referenced by WorldToRasterCoord.getURI().
st_worldToRasterCoordX
final URI st_worldToRasterCoordX =factory.createURI(NAMESPACE, "ST_WorldToRasterCoordX") static
Referenced by WorldToRasterCoordX.getURI().
st_worldToRasterCoordY
final URI st_worldToRasterCoordY =factory.createURI(NAMESPACE, "ST_WorldToRasterCoordY") static
Referenced by WorldToRasterCoordY.getURI().
st_x
final URI st_x =factory.createURI(NAMESPACE, "ST_X") static
Referenced by X.getURI().
st_xMax
final URI st_xMax =factory.createURI(NAMESPACE, "ST_XMax") static
Referenced by XMax.getURI().
st_xMin
final URI st_xMin =factory.createURI(NAMESPACE, "ST_XMin") static
Referenced by XMin.getURI().
st_y
final URI st_y =factory.createURI(NAMESPACE, "ST_Y") static
Referenced by Y.getURI().
st_yMax
final URI st_yMax =factory.createURI(NAMESPACE, "ST_YMax") static
Referenced by YMax.getURI().
st_yMin
final URI st_yMin =factory.createURI(NAMESPACE, "ST_YMin") static
Referenced by YMin.getURI().
st_z
final URI st_z =factory.createURI(NAMESPACE, "ST_Z") static
Referenced by Z.getURI().
st_zMax
final URI st_zMax =factory.createURI(NAMESPACE, "ST_ZMax") static
Referenced by ZMax.getURI().
st_zmFlag
final URI st_zmFlag =factory.createURI(NAMESPACE, "ST_Zmflag") static
Referenced by Zmflag.getURI().
st_zMin
final URI st_zMin =factory.createURI(NAMESPACE, "ST_ZMin") static
Referenced by ZMin.getURI().
SVG
final String SVG ="SVG" static
TemporalRange
final String TemporalRange ="TemporalRange" static
TopoJSON
final String TopoJSON = "TopoJSON" static
TWKB
final String TWKB = "TWKB" static
WKB
final String WKB = "WKB" static
WKBRaster
final String WKBRaster = "WKBRaster" static
WKT
final String WKT ="WKT" static
X3D
final String X3D = "X3D" static