kiwi-postgis: GeometricBinaryAttributeFunction Class Reference
GeometricBinaryAttributeFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
abstract boolean attribute (Geometry geom)
Member Function Documentation
attribute()
abstract boolean attribute (Geometry geom) abstract
Referenced by GeometricBinaryAttributeFunction.evaluate().
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References GeometricBinaryAttributeFunction.attribute(), and LiteralRegistry.getLiteral().
{
                 if (args.length != 1) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 1 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 if(l instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         boolean result = attribute(geom);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Argument given is not a geometry literal");
         }