kiwi-postgis: GeometricRelationBinaryFunction Class Reference
GeometricRelationBinaryFunction Class Reference abstract
Public Member Functions
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
Protected Member Functions
abstract boolean relation (Geometry g1, Geometry g2)
Member Function Documentation
evaluate()
Value evaluate (ValueFactory valueFactory, Value... args) throws ValueExprEvaluationException
References LiteralRegistry.getLiteral(), and GeometricRelationBinaryFunction.relation().
{
                 if (args.length != 2) {
                         throw new ValueExprEvaluationException(getURI() + " requires exactly 2 arguments, got " + args.length);
                 }
                 LiteralType l=LiteralRegistry.getLiteral(((Literal)args[0]).getDatatype().toString());
                 LiteralType l2=LiteralRegistry.getLiteral(((Literal)args[1]).getDatatype().toString());
                 if(l instanceof VectorLiteral && l2 instanceof VectorLiteral) {
                         Geometry geom=((VectorLiteral)l).read(args[0].stringValue());
                         Geometry geom2=((VectorLiteral)l2).read(args[1].stringValue());
                         boolean result = relation(geom,geom2);
                         return valueFactory.createLiteral(result);
                 }
                 throw new ValueExprEvaluationException("Arguments given are not a geometry literal");
         }
relation()
abstract boolean relation (Geometry g1, Geometry g2) abstract protected
Referenced by GeometricRelationBinaryFunction.evaluate().