kiwi-postgis: LiteralRegistry Class Reference
LiteralRegistry Class Reference
Public Member Functions
LiteralRegistry ()
Static Public Member Functions
static LiteralType getLiteral (String uri)
Static Public Attributes
static final Map< String, LiteralType > literals =new TreeMap<>()
static final LiteralRegistry INSTANCE =new LiteralRegistry()
Constructor & Destructor Documentation
LiteralRegistry()
LiteralRegistry ()
References NetCDFDatatype.INSTANCE, SVGDatatype.INSTANCE, GMLCOVDatatype.INSTANCE, GeoTIFFDatatype.INSTANCE, WKBRastDatatype.INSTANCE, CovJSONDatatype.INSTANCE, GeoURIDatatype.INSTANCE, WKTDatatype.INSTANCE, HexWKBRastDatatype.INSTANCE, PolyshapeDatatype.INSTANCE, KMLDatatype.INSTANCE, GeobufDatatype.INSTANCE, GPXDatatype.INSTANCE, HexWKBDatatype.INSTANCE, WKBDatatype.INSTANCE, TWKBDatatype.INSTANCE, EncodedPolylineDatatype.INSTANCE, DXFDatatype.INSTANCE, TopoJSONDatatype.INSTANCE, GMLDatatype.INSTANCE, GeoJSONDatatype.INSTANCE, NetCDFDatatype.URI, SVGDatatype.URI, GMLCOVDatatype.URI, GeoTIFFDatatype.URI, GeoURIDatatype.URI, WKTDatatype.URI, WKBRastDatatype.URI, CovJSONDatatype.URI, PolyshapeDatatype.URI, KMLDatatype.URI, HexWKBRastDatatype.URI, GeobufDatatype.URI, GPXDatatype.URI, HexWKBDatatype.URI, WKBDatatype.URI, TWKBDatatype.URI, EncodedPolylineDatatype.URI, DXFDatatype.URI, TopoJSONDatatype.URI, GMLDatatype.URI, and GeoJSONDatatype.URI.
{
                 literals.put(GMLDatatype.URI, GMLDatatype.INSTANCE);
                 literals.put(KMLDatatype.URI, KMLDatatype.INSTANCE);
                 literals.put(TWKBDatatype.URI, TWKBDatatype.INSTANCE);
                 literals.put(WKBDatatype.URI, WKBDatatype.INSTANCE);
                 literals.put(WKTDatatype.URI, WKTDatatype.INSTANCE);
                 literals.put(GeoJSONDatatype.URI, GeoJSONDatatype.INSTANCE);
                 literals.put(GeoURIDatatype.URI, GeoURIDatatype.INSTANCE);
                 literals.put(GPXDatatype.URI, GPXDatatype.INSTANCE);
                 literals.put(HexWKBDatatype.URI, HexWKBDatatype.INSTANCE);
                 literals.put(SVGDatatype.URI, SVGDatatype.INSTANCE);
                 literals.put(GeobufDatatype.URI, GeobufDatatype.INSTANCE);
                 literals.put(TopoJSONDatatype.URI, TopoJSONDatatype.INSTANCE);
                 literals.put(PolyshapeDatatype.URI, PolyshapeDatatype.INSTANCE);
                 literals.put(DXFDatatype.URI, DXFDatatype.INSTANCE);
                 literals.put(EncodedPolylineDatatype.URI, EncodedPolylineDatatype.INSTANCE);
                 literals.put(WKBRastDatatype.URI, WKBRastDatatype.INSTANCE);
                 literals.put(GeoTIFFDatatype.URI, GeoTIFFDatatype.INSTANCE);
                 literals.put(GMLCOVDatatype.URI, GMLCOVDatatype.INSTANCE);
                 literals.put(CovJSONDatatype.URI, CovJSONDatatype.INSTANCE);
                 literals.put(NetCDFDatatype.URI, NetCDFDatatype.INSTANCE);
                 literals.put(HexWKBRastDatatype.URI, HexWKBRastDatatype.INSTANCE);
         }
Member Function Documentation
getLiteral()
static LiteralType getLiteral (String uri) static
Referenced by GeometricBinaryFunction.evaluate(), GeometricConstructor.evaluate(), GeometricModifierFunction.evaluate(), RasterModifierIntIntFunction.evaluate(), RasterConstructorFunction.evaluate(), RasterModifierBoolDoubleFunction.evaluate(), RasterModifierDoubleDoubleFunction.evaluate(), GeometricModifierIntegerFunction.evaluate(), RasterModifierFunction.evaluate(), GeometricModifierStringFunction.evaluate(), GeometricConstructorInteger.evaluate(), RasterAttributeBooleanIntFunction.evaluate(), GeometricRelationBinaryFunction.evaluate(), GeometricRelationDoubleFunction.evaluate(), GeometricDoubleAttributeFunction.evaluate(), GeometricRelationIntegerFunction.evaluate(), GeometricRelationModifierFunction.evaluate(), GeometricDoubleModifierIntegerFunction.evaluate(), GeometricStringExportFunction.evaluate(), GeometricStringExportIntegerFunction.evaluate(), GeometricUnaryFunction.evaluate(), GeometricIntegerAttributeFunction.evaluate(), GeometricModifierDoubleFunction.evaluate(), GeometricBinaryAttributeFunction.evaluate(), GeometricModifierGeometryIntegerFunction.evaluate(), RasterAttributeIntIntDoubleFunction.evaluate(), RasterModifierGeometryFunction.evaluate(), RasterAttributeIntIntGeomFunction.evaluate(), GeometricEditFunction.evaluate(), Intersects.relation(), Overlaps.relation(), Contains.relation(), CoveredBy.relation(), Touches.relation(), Disjoint.relation(), Equals.relation(), Crosses.relation(), Within.relation(), Intersection.relation(), and ContainsProperly.relation().
{
                 if(literals.containsKey(uri)) {
                         return literals.get(uri);
                 }
                 return null;
         }
Member Data Documentation
INSTANCE
final LiteralRegistry INSTANCE =new LiteralRegistry() static
literals
final Map<String,LiteralType> literals =new TreeMap<>() static
Referenced by RasterVectorRelationBinaryFunction.vectorOrRaster().